Repository eclipse-capella/capella, pull requests merged in 2020-11, with the labels that each got.

#421 [567909] Fix IllegalStateException
  core/plugins/org.polarsys.capella.core.sirius.ui/src/org/polarsys/capella/core/sirius/ui/actions/MoveRepresentationsAction.java
Labels: build-unstable

#425 [Doc] Update API and M2 changes
  doc/plugins/org.polarsys.capella.doc/html/Release note/API_1.4.x_to_5.0.0.html
  doc/plugins/org.polarsys.capella.doc/html/Release note/API_1.4.x_to_5.0.0.mediawiki
  doc/plugins/org.polarsys.capella.doc/html/Release note/M2_1.4.x_to_5.0.0.html
  doc/plugins/org.polarsys.capella.doc/html/Release note/M2_1.4.x_to_5.0.0.mediawiki
  doc/plugins/org.polarsys.capella.doc/toc.xml
Labels: build-unstable

#422 [567909] Fix Commandline Junit regression
  tests/plugins/org.polarsys.capella.test.commandline.ju/src/org/polarsys/capella/test/commandline/ju/testcases/CommandLineRefreshAirdTest.java
Labels: build-unstable

#426 [releng][oomph] Sync target platform
  releng/plugins/org.polarsys.capella.settings/oomph/Capella.setup
Labels: build-unstable

#427 [568530] Icon for the menu Show Related Element(s) in Project Explorer disappears
  core/plugins/org.polarsys.capella.core.platform.sirius.ui.navigator/src/org/polarsys/capella/core/platform/sirius/ui/navigator/IImageKeys.java
  core/plugins/org.polarsys.capella.core.platform.sirius.ui.navigator/src/org/polarsys/capella/core/platform/sirius/ui/navigator/handlers/GotoRelatedElementsHandler.java
Labels: build-unstable

#428 [568561] Transition of State Machine raises error in some cases
  core/plugins/org.polarsys.capella.core.transition.system.topdown/src/org/polarsys/capella/core/transition/system/topdown/commands/TransitionCommandHelper.java
Labels: build-unstable

#435 [568684] RPL instantiation does not respect Physical Component
  core/plugins/org.polarsys.capella.core.model.helpers/src/org/polarsys/capella/core/model/helpers/ComponentExt.java
  core/plugins/org.polarsys.capella.core.model.helpers/src/org/polarsys/capella/core/model/helpers/ComponentPkgExt.java
  core/plugins/org.polarsys.capella.core.model.helpers/src/org/polarsys/capella/core/model/helpers/PartExt.java
  core/plugins/org.polarsys.capella.core.model.helpers/src/org/polarsys/capella/core/model/helpers/move/MoveHelper.java
  core/plugins/org.polarsys.capella.core.sirius.analysis/src/org/polarsys/capella/core/sirius/analysis/ABServices.java
  core/plugins/org.polarsys.capella.core.sirius.analysis/src/org/polarsys/capella/core/sirius/analysis/queries/csServices/GetABInsertComponentActor.java
  tests/plugins/org.polarsys.capella.test.framework/src/org/polarsys/capella/test/framework/context/SessionContext.java
  tests/plugins/org.polarsys.capella.test.navigator.ju/model/Component-Part-ComponentPkg-DragAndDrop/.project
  tests/plugins/org.polarsys.capella.test.navigator.ju/model/Component-Part-ComponentPkg-DragAndDrop/Component-Part-ComponentPkg-DragAndDrop.afm
  tests/plugins/org.polarsys.capella.test.navigator.ju/model/Component-Part-ComponentPkg-DragAndDrop/Component-Part-ComponentPkg-DragAndDrop.aird
  tests/plugins/org.polarsys.capella.test.navigator.ju/model/Component-Part-ComponentPkg-DragAndDrop/Component-Part-ComponentPkg-DragAndDrop.capella
  tests/plugins/org.polarsys.capella.test.navigator.ju/src/org/polarsys/capella/test/navigator/ju/dnd/AbstractDndTest.java
  tests/plugins/org.polarsys.capella.test.navigator.ju/src/org/polarsys/capella/test/navigator/ju/dnd/ComponentPartPkgDndOA.java
  tests/plugins/org.polarsys.capella.test.navigator.ju/src/org/polarsys/capella/test/navigator/ju/dnd/ComponentPartPkgDndPA.java
  tests/plugins/org.polarsys.capella.test.navigator.ju/src/org/polarsys/capella/test/navigator/ju/dnd/ComponentPartPkgDndSA.java
  tests/plugins/org.polarsys.capella.test.navigator.ju/src/org/polarsys/capella/test/navigator/ju/dnd/DnDTestSuite.java
  tests/plugins/org.polarsys.capella.test.navigator.ju/src/org/polarsys/capella/test/navigator/ju/testsuites/main/NavigatorUITestSuite.java
Labels: build-unstable

#436 [releng] Update Kitalpha version to 5.0.0-S202011101656
  releng/plugins/org.polarsys.capella.targets/full/capella.target-definition.targetplatform
Labels: build-unstable

#433 [568644] [Richtext] In read-only mode, users cannot see the full description
  core/plugins/org.polarsys.capella.core.ui.properties.richtext/src/org/polarsys/capella/core/ui/properties/richtext/fields/ElementDescriptionGroup.java
Labels: build-unstable

#430 [568583] Renaming the Instance Role should rename the Represented Instance and vice-versa for all scenario kinds
  core/plugins/org.polarsys.capella.core.model.helpers/src/org/polarsys/capella/core/model/helpers/listeners/CapellaModelDataListenerForInstanceRole.java
  core/plugins/org.polarsys.capella.core.model.helpers/src/org/polarsys/capella/core/model/helpers/listeners/CapellaModelDataListenerForPartsAndComponents.java
  core/plugins/org.polarsys.capella.core.model.helpers/src/org/polarsys/capella/core/model/helpers/listeners/CapellaModelEditingDomainListener.java
  core/plugins/org.polarsys.capella.core.model.helpers/src/org/polarsys/capella/core/model/utils/NamingHelper.java
  core/plugins/org.polarsys.capella.core.sirius.analysis/src/org/polarsys/capella/core/sequencediag/ScenarioService.java
Labels: build-unstable

#431 [568599] [Regression] The resulting CSV file after export to Excel of metrics on model is not sorted
  core/plugins/org.polarsys.capella.core.ui.metric/src/org/polarsys/capella/core/ui/metric/actions/MetricAction.java
  core/plugins/org.polarsys.capella.core.ui.metric/src/org/polarsys/capella/core/ui/metric/core/MetricTree.java
  tests/plugins/org.polarsys.capella.test.progressmonitoring.ju/build.properties
  tests/plugins/org.polarsys.capella.test.progressmonitoring.ju/src/org/polarsys/capella/test/progressmonitoring/ju/testcases/MetricTest.java
  tests/plugins/org.polarsys.capella.test.progressmonitoring.ju/testResult/epbsMetric.txt
  tests/plugins/org.polarsys.capella.test.progressmonitoring.ju/testResult/laMetric.txt
  tests/plugins/org.polarsys.capella.test.progressmonitoring.ju/testResult/oaMetric.txt
  tests/plugins/org.polarsys.capella.test.progressmonitoring.ju/testResult/paMetric.txt
  tests/plugins/org.polarsys.capella.test.progressmonitoring.ju/testResult/saMetric.txt
Labels: build-unstable

#434 [Doc] Update API and M2 changes
  doc/plugins/org.polarsys.capella.doc/html/Release note/API_1.4.0_to_1.4.x.html
  doc/plugins/org.polarsys.capella.doc/html/Release note/API_1.4.0_to_1.4.x.mediawiki
  doc/plugins/org.polarsys.capella.doc/html/Release note/API_1.4.x_to_5.0.0.html
  doc/plugins/org.polarsys.capella.doc/html/Release note/API_1.4.x_to_5.0.0.mediawiki
  doc/plugins/org.polarsys.capella.doc/html/Release note/M2_1.4.x_to_5.0.0.html
  doc/plugins/org.polarsys.capella.doc/html/Release note/M2_1.4.x_to_5.0.0.mediawiki
  doc/plugins/org.polarsys.capella.doc/toc.xml
Labels: build-unstable

#437 [568560] Update validation rule documentation
  core/plugins/org.polarsys.capella.core.data.interaction.validation/plugin.xml
  doc/plugins/org.polarsys.capella.validation.doc/html/Validation Rules/design/well-formedness/scenarios/ValidationRules.html
  doc/plugins/org.polarsys.capella.validation.doc/html/Validation Rules/design/well-formedness/scenarios/ValidationRules.mediawiki
Labels: build-unstable

#438 [568312] Fix Apply button on Project Page Properties
  core/plugins/org.polarsys.capella.core.preferences/src/org/polarsys/capella/core/commands/preferences/service/FieldEditorPropertyPreferencePage.java
  core/plugins/org.polarsys.capella.core.preferences/src/org/polarsys/capella/core/commands/preferences/service/PropertyStore.java
  tests/plugins/org.polarsys.capella.test.rcptt/PrefConfig/ValidationProfileActions.ctx
  tests/plugins/org.polarsys.capella.test.rcptt/PrefConfig/ValidationProfileSuite.suite
  tests/plugins/org.polarsys.capella.test.rcptt/PrefConfig/ValidationProfilesStep5.test
Labels: review-requested :lollipop:

#439 [568858] Enforce same name between Abstract Type Elements and their
  core/plugins/org.polarsys.capella.core.data.core.ui.quickfix/plugin.properties
  core/plugins/org.polarsys.capella.core.data.core.ui.quickfix/plugin.xml
  core/plugins/org.polarsys.capella.core.data.core.ui.quickfix/src/org/polarsys/capella/core/data/core/ui/quickfix/resolver/TypedElementHasDifferentNameThanTypeResolver.java
  core/plugins/org.polarsys.capella.core.data.core.validation/plugin.xml
  core/plugins/org.polarsys.capella.core.data.core.validation/src/org/polarsys/capella/core/data/core/validation/capellaelement/TypedElementHasDifferentNameThanType.java
  core/plugins/org.polarsys.capella.core.data.helpers/src/org/polarsys/capella/core/data/helpers/information/services/ExchangeItemExt.java
  core/plugins/org.polarsys.capella.core.model.helpers/src/org/polarsys/capella/core/model/helpers/listeners/CapellaModelDataListenerForExchangeItemAndExchangeItemInstance.java
  core/plugins/org.polarsys.capella.core.model.helpers/src/org/polarsys/capella/core/model/helpers/listeners/CapellaModelEditingDomainListener.java
  doc/plugins/org.polarsys.capella.validation.doc/html/Validation Rules/integrity/ValidationRules.html
  doc/plugins/org.polarsys.capella.validation.doc/html/Validation Rules/integrity/ValidationRules.mediawiki
  tests/plugins/org.polarsys.capella.test.validation.rules.ju/model/exchange-item-instance-and-part-model/.project
  tests/plugins/org.polarsys.capella.test.validation.rules.ju/model/exchange-item-instance-and-part-model/exchange-item-instance-and-part-model.afm
  tests/plugins/org.polarsys.capella.test.validation.rules.ju/model/exchange-item-instance-and-part-model/exchange-item-instance-and-part-model.aird
  tests/plugins/org.polarsys.capella.test.validation.rules.ju/model/exchange-item-instance-and-part-model/exchange-item-instance-and-part-model.capella
  tests/plugins/org.polarsys.capella.test.validation.rules.ju/src/org/polarsys/capella/test/validation/rules/ju/testcases/i/IRulesTestSuite.java
  tests/plugins/org.polarsys.capella.test.validation.rules.ju/src/org/polarsys/capella/test/validation/rules/ju/testcases/i/Rule_I_45.java
Labels: build-unstable

#443 [568983] Project renaming fails for names containing non-alphanumerical
  core/plugins/org.polarsys.capella.core.platform.sirius.ui.navigator/src/org/polarsys/capella/core/platform/sirius/ui/navigator/actions/RenameResourceAction.java
  doc/plugins/org.polarsys.capella.ui.doc/html/03. First steps with Capella/3.7. How to rename a Capella Project.html
  doc/plugins/org.polarsys.capella.ui.doc/html/03. First steps with Capella/3.7. How to rename a Capella Project.mediawiki
  tests/plugins/org.polarsys.capella.test.model.ju/model/[rename model]/.project
  tests/plugins/org.polarsys.capella.test.model.ju/model/[rename model]/[rename model].afm
  tests/plugins/org.polarsys.capella.test.model.ju/model/[rename model]/[rename model].aird
  tests/plugins/org.polarsys.capella.test.model.ju/model/[rename model]/[rename model].capella
  tests/plugins/org.polarsys.capella.test.model.ju/model/[rename model]/fragments/[OA].airdfragment
  tests/plugins/org.polarsys.capella.test.model.ju/model/[rename model]/fragments/[OA].capellafragment
  tests/plugins/org.polarsys.capella.test.model.ju/src/org/polarsys/capella/test/model/ju/rename/RenameModelTestSuite.java
  tests/plugins/org.polarsys.capella.test.model.ju/src/org/polarsys/capella/test/model/ju/rename/RenameSpecialCharTestCase.java
Labels: build-unstable, to: squash :cookie:

#446 [569062] Forbid Project creation or Resource renaming for names
  core/plugins/org.polarsys.capella.core.model.handler/META-INF/MANIFEST.MF
  core/plugins/org.polarsys.capella.core.model.handler/src/org/polarsys/capella/core/model/handler/command/CapellaResourceNamingHelper.java
  core/plugins/org.polarsys.capella.core.model.handler/src/org/polarsys/capella/core/model/handler/command/Messages.java
  core/plugins/org.polarsys.capella.core.model.handler/src/org/polarsys/capella/core/model/handler/command/messages.properties
  core/plugins/org.polarsys.capella.core.platform.sirius.ui.navigator/src/org/polarsys/capella/core/platform/sirius/ui/navigator/actions/RenameResourceAction.java
  core/plugins/org.polarsys.capella.core.platform.sirius.ui.project/src/org/polarsys/capella/core/platform/sirius/ui/project/internal/WizardNewProjectCreationPage.java
  core/plugins/org.polarsys.capella.core.preferences.project.configuration/src/org/polarsys/capella/core/preferences/configuration/project/WizardProjectCreationPage.java
  tests/plugins/org.polarsys.capella.test.model.ju/src/org/polarsys/capella/test/model/ju/helpers/CapellaResourceNamingHelperTestCase.java
  tests/plugins/org.polarsys.capella.test.model.ju/src/org/polarsys/capella/test/model/ju/testsuites/main/ModelTestSuite.java
Labels: build-unstable

#445 [releng] Update Sirius version to 6.4.0-S20201119-043506
  releng/plugins/org.polarsys.capella.settings/oomph/Capella.setup
  releng/plugins/org.polarsys.capella.targets/full/capella.target-definition.targetplatform
Labels: build-unstable

#444 [567249] Enter enabled on selecting an element
  core/plugins/org.polarsys.capella.core.platform.eclipse.ui.trace/src/org/polarsys/capella/core/platform/eclipse/capella/ui/trace/views/TraceTreeSelectionDialog.java
  core/plugins/org.polarsys.capella.core.platform.eclipse.ui.trace/src/org/polarsys/capella/core/platform/eclipse/capella/ui/trace/views/components/TraceTreeViewer.java
  core/plugins/org.polarsys.capella.core.platform.eclipse.ui.trace/src/org/polarsys/capella/core/platform/eclipse/capella/ui/trace/views/providers/CapellaModelFilter.java
Labels: build-unstable

#448 [568858] Fix wrong namespaceUri for the validation rule
  core/plugins/org.polarsys.capella.core.data.core.validation/plugin.xml
Labels: build-unstable

#449 [569167] Capability transition does not work for involved components/actors and other capability relations
  core/plugins/org.polarsys.capella.core.transition.system.topdown/plugin.xml
  core/plugins/org.polarsys.capella.core.transition.system.topdown/src/org/polarsys/capella/core/transition/system/topdown/commands/IntramodelTransitionCommand.java
  core/plugins/org.polarsys.capella.core.transition.system.topdown/src/org/polarsys/capella/core/transition/system/topdown/handlers/transformation/TopDownTransformationHelper.java
  core/plugins/org.polarsys.capella.core.transition.system.topdown/src/org/polarsys/capella/core/transition/system/topdown/rules/interaction/AbstractCapabilityExtendRule.java
  core/plugins/org.polarsys.capella.core.transition.system.topdown/src/org/polarsys/capella/core/transition/system/topdown/rules/interaction/AbstractCapabilityGeneralizationRule.java
  core/plugins/org.polarsys.capella.core.transition.system.topdown/src/org/polarsys/capella/core/transition/system/topdown/rules/interaction/AbstractCapabilityIncludeRule.java
  core/plugins/org.polarsys.capella.core.transition.system.topdown/src/org/polarsys/capella/core/transition/system/topdown/rules/interaction/AbstractCapabilityRule.java
  core/plugins/org.polarsys.capella.core.transition.system.topdown/src/org/polarsys/capella/core/transition/system/topdown/rules/interaction/CapabilityInvolvementRule.java
  core/plugins/org.polarsys.capella.core.transition.system.topdown/src/org/polarsys/capella/core/transition/system/topdown/rules/oa/capability/EntityRule.java
  core/plugins/org.polarsys.capella.core.transition.system/src/org/polarsys/capella/core/transition/system/rules/interaction/AbstractCapabilityExtendRule.java
  core/plugins/org.polarsys.capella.core.transition.system/src/org/polarsys/capella/core/transition/system/rules/interaction/AbstractCapabilityIncludeRule.java
  tests/plugins/org.polarsys.capella.test.transition.ju/model/AllProjectionModels/AllProjectionModels.aird
  tests/plugins/org.polarsys.capella.test.transition.ju/model/AllProjectionModels/AllProjectionModels.capella
  tests/plugins/org.polarsys.capella.test.transition.ju/src/org/polarsys/capella/test/transition/ju/model/ModelLaPa.java
  tests/plugins/org.polarsys.capella.test.transition.ju/src/org/polarsys/capella/test/transition/ju/model/ModelOaSa.java
  tests/plugins/org.polarsys.capella.test.transition.ju/src/org/polarsys/capella/test/transition/ju/testcases/la/ActorTransition.java
  tests/plugins/org.polarsys.capella.test.transition.ju/src/org/polarsys/capella/test/transition/ju/testcases/la/CapabilityTransition.java
  tests/plugins/org.polarsys.capella.test.transition.ju/src/org/polarsys/capella/test/transition/ju/testcases/oa/CapabilityTransition.java
  tests/plugins/org.polarsys.capella.test.transition.ju/src/org/polarsys/capella/test/transition/ju/testcases/sa/CapabilityTransition.java
Labels: build-unstable

#447 [releng] Update Kitalpha version to 5.0.0-S202011241439
  releng/plugins/org.polarsys.capella.targets/full/capella.target-definition.targetplatform
Labels: build-unstable
