Repository eclipse-capella/capella, pull requests merged in 2020-10, with the labels that each got.

#341 [566437] Use IllegalStateExceptionQuery where it is necessary
  common/plugins/org.polarsys.capella.common.ui/src/org/polarsys/capella/common/ui/providers/MDEAdapterFactoryLabelProvider.java
  core/plugins/org.polarsys.capella.core.model.handler/src/org/polarsys/capella/core/model/handler/helpers/CapellaAdapterHelper.java
  core/plugins/org.polarsys.capella.core.platform.sirius.ui.navigator/src/org/polarsys/capella/core/platform/sirius/ui/navigator/actions/CloneAction.java
  core/plugins/org.polarsys.capella.core.platform.sirius.ui.navigator/src/org/polarsys/capella/core/platform/sirius/ui/navigator/actions/move/representation/MoveRepresentationMenuManager.java
  core/plugins/org.polarsys.capella.core.platform.sirius.ui.navigator/src/org/polarsys/capella/core/platform/sirius/ui/navigator/viewer/CapellaNavigatorLabelProvider.java
  core/plugins/org.polarsys.capella.core.sirius.ui/src/org/polarsys/capella/core/sirius/ui/actions/OpenRepresentationsAction.java
  core/plugins/org.polarsys.capella.core.sirius.ui/src/org/polarsys/capella/core/sirius/ui/actions/RenameRepresentationAction.java
  core/plugins/org.polarsys.capella.core.ui.properties.richtext/src/org/polarsys/capella/core/ui/properties/richtext/fields/ElementDescriptionGroup.java
  core/plugins/org.polarsys.capella.core.ui.properties.richtext/src/org/polarsys/capella/core/ui/properties/richtext/sections/CapellaDescriptionPropertySection.java
  core/plugins/org.polarsys.capella.core.ui.properties/src/org/polarsys/capella/core/ui/properties/TabbedPropertiesLabelProvider.java
  core/plugins/org.polarsys.capella.core.ui.semantic.browser/src/org/polarsys/capella/core/ui/semantic/browser/view/SemanticBrowserView.java
Labels: build-unstable

#377 [Doc] Add more details about changing JDK version and a trouble shooting section
  doc/plugins/org.polarsys.capella.ui.doc/html/Installation Guide/How to install Capella and Addons.html
  doc/plugins/org.polarsys.capella.ui.doc/html/Installation Guide/How to install Capella and Addons.mediawiki
  doc/plugins/org.polarsys.capella.ui.doc/html/Installation Guide/Images/LaunchingPopup.png
  doc/plugins/org.polarsys.capella.ui.doc/license.txt
Labels: build-unstable

#393 [567249] Unable to use filtering in Trace Manager during selection of trace element
  core/plugins/org.polarsys.capella.core.platform.eclipse.ui.trace/build.properties
Labels: build-unstable

#399 [cleanup] Avoid NPEs in diagram property sections when diagrams or descriptors are no more available
  core/plugins/org.polarsys.capella.core.ui.properties/src/org/polarsys/capella/core/ui/properties/sections/DiagramRepresentationPropertySection.java
Labels: build-unstable

#403 [567412] Revert the change to migrate .melodyconnector to .capellaconnector
  core/plugins/org.polarsys.capella.core.model.handler/src/org/polarsys/capella/core/model/handler/command/CapellaResourceHelper.java
Labels: build-unstable

#373 [567246] Add a warning message in the DeleteCapellaElement dialog box
  core/plugins/org.polarsys.capella.core.platform.sirius.ui.actions/src/org/polarsys/capella/core/platform/sirius/ui/commands/CapellaDeleteCommand.java
  core/plugins/org.polarsys.capella.core.platform.sirius.ui.actions/src/org/polarsys/capella/core/platform/sirius/ui/commands/Messages.java
  core/plugins/org.polarsys.capella.core.platform.sirius.ui.actions/src/org/polarsys/capella/core/platform/sirius/ui/commands/messages.properties
  core/plugins/org.polarsys.capella.core.ui.toolkit/src/org/polarsys/capella/core/ui/toolkit/dialogs/ConfirmDeleteCapellaElementDialog.java
Labels: build-unstable, to: double-review :recycle:, to: squash :cookie:

#406 [567246] Without an OK Status the delete doesn't complete
  core/plugins/org.polarsys.capella.core.model.handler/src/org/polarsys/capella/core/model/handler/command/BasicCapellaDeleteCommand.java
Labels: build-unstable, to: rebase-and-merge :doughnut:

#409 [rcptt] Fix failing RCPTT tests
  core/plugins/org.polarsys.capella.core.explorer.activity.ui/src/org/polarsys/capella/core/explorer/activity/ui/pages/AbstractCapellaPage.java
  core/plugins/org.polarsys.capella.core.explorer.activity.ui/src/org/polarsys/capella/core/explorer/activity/ui/viewer/CapellaDiagramViewer.java
  tests/plugins/org.polarsys.capella.test.explorer.activity.ju/META-INF/MANIFEST.MF
  tests/plugins/org.polarsys.capella.test.explorer.activity.ju/src/org/polarsys/capella/test/explorer/activity/ju/testcases/CheckRightClickActions.java
  tests/plugins/org.polarsys.capella.test.explorer.activity.ju/src/org/polarsys/capella/test/explorer/activity/ju/testsuites/ActivityExplorerTestsSuite.java
  tests/plugins/org.polarsys.capella.test.rcptt/ActivityExplorer/ActivityExplorerSuite.suite
  tests/plugins/org.polarsys.capella.test.rcptt/ActivityExplorer/DiagramCreation.test
  tests/plugins/org.polarsys.capella.test.rcptt/ActivityExplorer/DiagramViewer.test
  tests/plugins/org.polarsys.capella.test.rcptt/ActivityExplorer/MoveRepresentationInActivityExplorer.test
  tests/plugins/org.polarsys.capella.test.rcptt/AllTests.suite
  tests/plugins/org.polarsys.capella.test.rcptt/Constraint/Pre_Post_Conditions_FS_diagram.test
  tests/plugins/org.polarsys.capella.test.rcptt/CopyPasteCut/CopyPasteNoDuplicatedElements.test
  tests/plugins/org.polarsys.capella.test.rcptt/ExchangeItemScenario/ExchangeItemScenario.test
  tests/plugins/org.polarsys.capella.test.rcptt/Library/AccessPolicyRecRpl.test
  tests/plugins/org.polarsys.capella.test.rcptt/Menu/MoveRepresentation.test
  tests/plugins/org.polarsys.capella.test.rcptt/PrefConfig/ValidationProfileActions.ctx
  tests/plugins/org.polarsys.capella.test.rcptt/PrefConfig/ValidationProfiles.test
  tests/plugins/org.polarsys.capella.test.rcptt/PrefConfig/ValidationProfilesStep2.test
  tests/plugins/org.polarsys.capella.test.rcptt/PrefConfig/ValidationProfilesStep3.test
  tests/plugins/org.polarsys.capella.test.rcptt/RecRpl/ARecRplSetSuffix.test
  tests/plugins/org.polarsys.capella.test.rcptt/RecRpl/RecRpl.test
  tests/plugins/org.polarsys.capella.test.rcptt/SemanticBrowser/SemanticBrowserHistory.test
  tests/plugins/org.polarsys.capella.test.rcptt/SemanticBrowser/SemanticBrowserSelection.test
  tests/plugins/org.polarsys.capella.test.rcptt/SemanticBrowser/SemanticBrowserShowIn.test
  tests/plugins/org.polarsys.capella.test.rcptt/SiriusUiNavigator/RefreshAllSubRepresentations_Complex.test
  tests/plugins/org.polarsys.capella.test.rcptt/SiriusUiNavigator/RefreshAllSubRepresentations_Simple.test
Labels: build-unstable

#410 [doc] Rename legacy references to product files
  doc/plugins/org.polarsys.capella.commandline.doc/html/19. Command Line Support/19.1. Core Mechanism and Applications.html
  doc/plugins/org.polarsys.capella.commandline.doc/html/19. Command Line Support/19.1. Core Mechanism and Applications.mediawiki
  doc/plugins/org.polarsys.capella.preferences.doc/html/06. Preferences/6.5. Usage Monitoring.html
  doc/plugins/org.polarsys.capella.preferences.doc/html/06. Preferences/6.5. Usage Monitoring.mediawiki
  doc/plugins/org.polarsys.capella.th.doc/.settings/org.eclipse.core.resources.prefs
  doc/plugins/org.polarsys.capella.th.doc/html/Performance Recommandations/Images/Perf_REC9.png
  doc/plugins/org.polarsys.capella.th.doc/html/Performance Recommandations/Performance Recommandations-toc.xml
  doc/plugins/org.polarsys.capella.th.doc/html/Performance Recommandations/Performance Recommandations.html
  doc/plugins/org.polarsys.capella.th.doc/html/Performance Recommandations/Performance Recommandations.mediawiki
  doc/plugins/org.polarsys.capella.th.doc/license.txt
  doc/plugins/org.polarsys.capella.ui.doc/html/04. User Interface/4.06. Properties View.html
  doc/plugins/org.polarsys.capella.ui.doc/html/04. User Interface/4.06. Properties View.mediawiki
  doc/plugins/org.polarsys.capella.ui.doc/html/Installation Guide/How to install Capella and Addons.html
  doc/plugins/org.polarsys.capella.ui.doc/html/Installation Guide/How to install Capella and Addons.mediawiki
  doc/plugins/org.polarsys.capella.ui.doc/html/Installation Guide/Images/3.9. How to install Cappela and Addons_Multicontext_Install.png
Labels: build-started

#412 [releng] Update to Amalgam 1.12.0-S20201020
  releng/plugins/org.polarsys.capella.targets/full/capella.target-definition.targetplatform
Labels: build-unstable, review-requested :lollipop:

#413 [Releng] Clean up Orbit dependencies and MANIFESTs to use latest COTS version found in Eclipse update site
  common/plugins/org.polarsys.capella.common.linkedtext.ui/META-INF/MANIFEST.MF
  common/plugins/org.polarsys.capella.common.re/META-INF/MANIFEST.MF
  common/plugins/org.polarsys.capella.common/META-INF/MANIFEST.MF
  core/plugins/org.polarsys.capella.core.data.common.validation/META-INF/MANIFEST.MF
  core/plugins/org.polarsys.capella.core.data.information.datavalue.properties/META-INF/MANIFEST.MF
  core/plugins/org.polarsys.capella.core.libraries.ui/META-INF/MANIFEST.MF
  core/plugins/org.polarsys.capella.core.re.updateconnections.ui/META-INF/MANIFEST.MF
  core/plugins/org.polarsys.capella.core.re.validation/META-INF/MANIFEST.MF
  releng/plugins/org.polarsys.capella.targets/full/capella.target-definition.targetplatform
Labels: build-unstable

#414 [releng] Use Diffmerge 0.13.0-M4
  releng/plugins/org.polarsys.capella.targets/full/capella.target-definition.targetplatform
Labels: build-unstable

#339 [566434] Always call SemanticBrowserView.setInput in UI Thread
  core/plugins/org.polarsys.capella.core.ui.semantic.browser/src/org/polarsys/capella/core/ui/semantic/browser/view/SemanticBrowserView.java
Labels: build-unstable, to: squash :cookie:

#381 [563193] Capella Diagram Performance issues
  core/plugins/org.polarsys.capella.core.sirius.analysis/plugin.xml
  core/plugins/org.polarsys.capella.core.sirius.analysis/src/org/polarsys/capella/core/sequencediag/ScenarioService.java
  core/plugins/org.polarsys.capella.core.sirius.analysis/src/org/polarsys/capella/core/sirius/analysis/SequenceDiagramServices.java
  core/plugins/org.polarsys.capella.core.sirius.analysis/src/org/polarsys/capella/core/sirius/analysis/cache/ScenarioCache.java
  core/plugins/org.polarsys.capella.core.sirius.analysis/src/org/polarsys/capella/core/sirius/analysis/refresh/extension/ScenarioRefreshExtension.java
  core/plugins/org.polarsys.capella.core.sirius.analysis/src/org/polarsys/capella/core/sirius/analysis/refresh/extension/ScenarioRefreshExtensionProvider.java
Labels: build-unstable

#415 [568104] Add the activity "Component Deployment"
  core/plugins/org.polarsys.capella.core.platform.sirius.ui.perspective/plugin.xml
Labels: build-unstable

#420 [releng] Update target platform to Sirius
  common/plugins/org.polarsys.capella.common.platform.sirius.customization/src/org/polarsys/capella/common/platform/sirius/customisation/uicallback/SiriusUiCallBack.java
  releng/plugins/org.polarsys.capella.settings/oomph/Capella.setup
  releng/plugins/org.polarsys.capella.targets/full/capella.target-definition.targetplatform
Labels: build-unstable

#417 [568294] A newly created element may not be focused by default
  core/plugins/org.polarsys.capella.core.platform.sirius.ui.navigator/src/org/polarsys/capella/core/platform/sirius/ui/navigator/viewer/CapellaNavigatorContentProvider.java
Labels: build-unstable, review-requested :lollipop:

#418 [568298] OAIB Removing operational activity from diagram results in interactions between child OA and parent OA
  common/plugins/org.polarsys.capella.common/src/org/polarsys/capella/common/helpers/EcoreUtil2.java
  core/plugins/org.polarsys.capella.core.sirius.analysis/src/org/polarsys/capella/core/sirius/analysis/OAServices.java
  tests/plugins/org.polarsys.capella.test.diagram.misc.ju/model/StatusLine/StatusLine.aird
  tests/plugins/org.polarsys.capella.test.diagram.misc.ju/model/StatusLine/StatusLine.capella
  tests/plugins/org.polarsys.capella.test.diagram.misc.ju/src/org/polarsys/capella/test/diagram/misc/ju/testcases/InteractionSourceTarget.java
  tests/plugins/org.polarsys.capella.test.diagram.misc.ju/src/org/polarsys/capella/test/diagram/misc/ju/testsuites/DiagramMiscTestSuite.java
Labels: build-aborted, build-unstable, review-requested :lollipop:
