Repository eclipse-capella/capella, pull requests merged in 2020-05, with the labels that each got.

#195 [releng] Avoid use archived orbit repository
  releng/plugins/org.polarsys.capella.targets/full/capella.target-definition.targetplatform
Labels: review-requested :lollipop:

#169 [561365] Update IFE sample description
  samples/In-Flight Entertainment System/In-Flight Entertainment System.melodymodeller
Labels: review-requested :lollipop:

#203 Bugzilla/558030/search and replace
  Jenkinsfile
  core/plugins/org.polarsys.capella.core.ui.search/.settings/org.eclipse.jdt.ui.prefs
  core/plugins/org.polarsys.capella.core.ui.search/META-INF/MANIFEST.MF
  core/plugins/org.polarsys.capella.core.ui.search/build.properties
  core/plugins/org.polarsys.capella.core.ui.search/icons/check_all.png
  core/plugins/org.polarsys.capella.core.ui.search/icons/license.txt
  core/plugins/org.polarsys.capella.core.ui.search/icons/line_match.png
  core/plugins/org.polarsys.capella.core.ui.search/icons/uncheck_all.png
  core/plugins/org.polarsys.capella.core.ui.search/plugin.xml
  core/plugins/org.polarsys.capella.core.ui.search/src/org/polarsys/capella/core/ui/search/AbstractCapellaHistory.java
  core/plugins/org.polarsys.capella.core.ui.search/src/org/polarsys/capella/core/ui/search/Activator.java
  core/plugins/org.polarsys.capella.core.ui.search/src/org/polarsys/capella/core/ui/search/CapellaReplaceDialog.java
  core/plugins/org.polarsys.capella.core.ui.search/src/org/polarsys/capella/core/ui/search/CapellaReplaceHistory.java
  core/plugins/org.polarsys.capella.core.ui.search/src/org/polarsys/capella/core/ui/search/CapellaReplaceQuery.java
  core/plugins/org.polarsys.capella.core.ui.search/src/org/polarsys/capella/core/ui/search/CapellaReplaceRunnable.java
  core/plugins/org.polarsys.capella.core.ui.search/src/org/polarsys/capella/core/ui/search/CapellaReplaceRunnableWrapper.java
  core/plugins/org.polarsys.capella.core.ui.search/src/org/polarsys/capella/core/ui/search/CapellaSearchConstants.java
  core/plugins/org.polarsys.capella.core.ui.search/src/org/polarsys/capella/core/ui/search/CapellaSearchPage.java
  core/plugins/org.polarsys.capella.core.ui.search/src/org/polarsys/capella/core/ui/search/CapellaSearchQuery.java
  core/plugins/org.polarsys.capella.core.ui.search/src/org/polarsys/capella/core/ui/search/CapellaSearchResult.java
  core/plugins/org.polarsys.capella.core.ui.search/src/org/polarsys/capella/core/ui/search/CapellaSearchResultLabelProvider.java
  core/plugins/org.polarsys.capella.core.ui.search/src/org/polarsys/capella/core/ui/search/CapellaSearchResultListContentProvider.java
  core/plugins/org.polarsys.capella.core.ui.search/src/org/polarsys/capella/core/ui/search/CapellaSearchResultPage.java
  core/plugins/org.polarsys.capella.core.ui.search/src/org/polarsys/capella/core/ui/search/CapellaSearchResultPageHandlerReplaceAll.java
  core/plugins/org.polarsys.capella.core.ui.search/src/org/polarsys/capella/core/ui/search/CapellaSearchResultPageHandlerReplaceSelected.java
  core/plugins/org.polarsys.capella.core.ui.search/src/org/polarsys/capella/core/ui/search/CapellaSearchResultPageHandlerSelect.java
  core/plugins/org.polarsys.capella.core.ui.search/src/org/polarsys/capella/core/ui/search/CapellaSearchResultTreeContentProvider.java
  core/plugins/org.polarsys.capella.core.ui.search/src/org/polarsys/capella/core/ui/search/CapellaSearchSettings.java
  core/plugins/org.polarsys.capella.core.ui.search/src/org/polarsys/capella/core/ui/search/CapellaSearchSettingsHistory.java
  core/plugins/org.polarsys.capella.core.ui.search/src/org/polarsys/capella/core/ui/search/CapellaUISearchPlugin.java
  core/plugins/org.polarsys.capella.core.ui.search/src/org/polarsys/capella/core/ui/search/CommandFactory.java
  core/plugins/org.polarsys.capella.core.ui.search/src/org/polarsys/capella/core/ui/search/FindAndReplaceDialog.java
  core/plugins/org.polarsys.capella.core.ui.search/src/org/polarsys/capella/core/ui/search/FindAndReplaceHeader.java
  core/plugins/org.polarsys.capella.core.ui.search/src/org/polarsys/capella/core/ui/search/Messages.java
  core/plugins/org.polarsys.capella.core.ui.search/src/org/polarsys/capella/core/ui/search/PatternFactory.java
  core/plugins/org.polarsys.capella.core.ui.search/src/org/polarsys/capella/core/ui/search/ReplaceInDescriptionSaxParser.java
  core/plugins/org.polarsys.capella.core.ui.search/src/org/polarsys/capella/core/ui/search/handler/FindReplaceHandler.java
  core/plugins/org.polarsys.capella.core.ui.search/src/org/polarsys/capella/core/ui/search/match/LineSearchMatchChild.java
  core/plugins/org.polarsys.capella.core.ui.search/src/org/polarsys/capella/core/ui/search/match/ListElementSearchMatchChild.java
  core/plugins/org.polarsys.capella.core.ui.search/src/org/polarsys/capella/core/ui/search/match/SearchMatch.java
  core/plugins/org.polarsys.capella.core.ui.search/src/org/polarsys/capella/core/ui/search/match/SearchMatchChild.java
  core/plugins/org.polarsys.capella.core.ui.search/src/org/polarsys/capella/core/ui/search/messages.properties
  core/plugins/org.polarsys.capella.core.ui.search/src/org/polarsys/capella/core/ui/search/searchfor/AbstractCapellaSearchForContainerArea.java
  core/plugins/org.polarsys.capella.core.ui.search/src/org/polarsys/capella/core/ui/search/searchfor/AbstractSearchForContentProvider.java
  core/plugins/org.polarsys.capella.core.ui.search/src/org/polarsys/capella/core/ui/search/searchfor/AttributeContentProvider.java
  core/plugins/org.polarsys.capella.core.ui.search/src/org/polarsys/capella/core/ui/search/searchfor/CapellaLeftSearchForContainerArea.java
  core/plugins/org.polarsys.capella.core.ui.search/src/org/polarsys/capella/core/ui/search/searchfor/CapellaRightSearchForContainerArea.java
  core/plugins/org.polarsys.capella.core.ui.search/src/org/polarsys/capella/core/ui/search/searchfor/CheckboxFilteredTree.java
  core/plugins/org.polarsys.capella.core.ui.search/src/org/polarsys/capella/core/ui/search/searchfor/ClassContentProvider.java
  core/plugins/org.polarsys.capella.core.ui.search/src/org/polarsys/capella/core/ui/search/searchfor/GetImagesFromEClassUtil.java
  core/plugins/org.polarsys.capella.core.ui.search/src/org/polarsys/capella/core/ui/search/searchfor/SearchForItemCache.java
  core/plugins/org.polarsys.capella.core.ui.search/src/org/polarsys/capella/core/ui/search/searchfor/SearchForLabelProvider.java
  core/plugins/org.polarsys.capella.core.ui.search/src/org/polarsys/capella/core/ui/search/searchfor/item/SearchForAttributeItem.java
  core/plugins/org.polarsys.capella.core.ui.search/src/org/polarsys/capella/core/ui/search/searchfor/item/SearchForClassItem.java
  core/plugins/org.polarsys.capella.core.ui.search/src/org/polarsys/capella/core/ui/search/searchfor/item/SearchForDiagramItem.java
  core/plugins/org.polarsys.capella.core.ui.search/src/org/polarsys/capella/core/ui/search/searchfor/item/SearchForItem.java
  core/plugins/org.polarsys.capella.core.ui.search/src/org/polarsys/capella/core/ui/search/searchfor/item/SearchForNoteItem.java
Labels: review-requested :lollipop:

#200 [tests] Update RCPTT
  tests/plugins/org.polarsys.capella.test.rcptt/ActivityExplorer/DiagramCreation.test
  tests/plugins/org.polarsys.capella.test.rcptt/ActivityExplorer/MoveRepresentationInActivityExplorer.test
  tests/plugins/org.polarsys.capella.test.rcptt/ActivityExplorer/OpenClose.test
  tests/plugins/org.polarsys.capella.test.rcptt/CopyPasteCut/CutDiagramElements.test
  tests/plugins/org.polarsys.capella.test.rcptt/DiffMerge/LocalFragmentedModel.test
  tests/plugins/org.polarsys.capella.test.rcptt/InnerDiagrams/DeleteSystemFunction.test
  tests/plugins/org.polarsys.capella.test.rcptt/Library/AccessPolicyRecRpl.test
  tests/plugins/org.polarsys.capella.test.rcptt/Migration/CheckAFMFilePresenceAfterMigration.test
  tests/plugins/org.polarsys.capella.test.rcptt/Patterns/MultiApplyPatternFromAnotherProject.test
  tests/plugins/org.polarsys.capella.test.rcptt/Patterns/speficHelpers/PatternsHelper.ctx
  tests/plugins/org.polarsys.capella.test.rcptt/PrefConfig/ValidationProfileActions.ctx
  tests/plugins/org.polarsys.capella.test.rcptt/RecRpl/RecRpl.test
  tests/plugins/org.polarsys.capella.test.rcptt/SemanticBrowser/SemanticBrowserDoubleClickOnElement.test
  tests/plugins/org.polarsys.capella.test.rcptt/Sequence/FunctionalExchangeWhenAllocationWithoutTarget.test
  tests/plugins/org.polarsys.capella.test.rcptt/Sequence/LifelineDeletion.test
  tests/plugins/org.polarsys.capella.test.rcptt/Sequence/PrePostConditionDeletionImpactAnalysis.test
  tests/plugins/org.polarsys.capella.test.rcptt/SiriusUiNavigator/RefreshAllSubRepresentations_Complex.test
  tests/plugins/org.polarsys.capella.test.rcptt/SiriusUiNavigator/RefreshAllSubRepresentations_Simple.test
  tests/plugins/org.polarsys.capella.test.rcptt/ValidationProfile/ProjectConfiguration.test
Labels: review-requested :lollipop:

#202 IS changes
  core/plugins/org.polarsys.capella.core.sirius.analysis/description/common.odesign
Labels: review-requested :lollipop:

#175 [561513] Add missing feature egit.mylyn
  core/features/org.polarsys.capella.core.mylyn.feature/feature.xml
  releng/plugins/org.polarsys.capella.targets/full/capella.target-definition.targetplatform
Labels: review-requested :lollipop:

#212 [563087] Insert/Remove components on IS shows InstanceRoles instead of represented instances
  core/plugins/org.polarsys.capella.core.sirius.analysis/description/common.odesign
Labels: review-requested :lollipop:

#213 [563293] SelectionDialogHelper.simplePropertiesSelectionDialogWizard doesn't allow multiple selection
  core/plugins/org.polarsys.capella.core.ui.toolkit/src/org/polarsys/capella/core/ui/toolkit/helpers/SelectionDialogHelper.java
Labels: review-requested :lollipop:

#215 [562503] OAIB Insert Remove Operational Activities wrongly filters activities allocated to actors
  core/plugins/org.polarsys.capella.core.sirius.analysis/description/oa.odesign
  tests/plugins/org.polarsys.capella.test.diagram.common.ju/src/org/polarsys/capella/test/diagram/common/ju/step/tools/InsertRemoveTool.java
  tests/plugins/org.polarsys.capella.test.diagram.tools.ju/model/XDFBToolsTestingModel/XDFBToolsTestingModel.melodymodeller
  tests/plugins/org.polarsys.capella.test.diagram.tools.ju/src/org/polarsys/capella/test/diagram/tools/ju/model/XDFBToolsTestingModel.java
  tests/plugins/org.polarsys.capella.test.diagram.tools.ju/src/org/polarsys/capella/test/diagram/tools/ju/xdfb/XDFBShowHideFunctions.java
Labels: review-requested :lollipop:

#214 [561395] Exception is raised when trying to manage references for a model with broken reference to a library (#158)
  core/plugins/org.polarsys.capella.core.data.common.validation/META-INF/MANIFEST.MF
  core/plugins/org.polarsys.capella.core.data.common.validation/plugin.xml
  core/plugins/org.polarsys.capella.core.data.common.validation/src/org/polarsys/capella/core/data/common/validation/project/ProjectReferencedLibrariesRule.java
  core/plugins/org.polarsys.capella.core.data.core.ui.quickfix/META-INF/MANIFEST.MF
  core/plugins/org.polarsys.capella.core.data.core.ui.quickfix/plugin.properties
  core/plugins/org.polarsys.capella.core.data.core.ui.quickfix/plugin.xml
  core/plugins/org.polarsys.capella.core.data.core.ui.quickfix/src/org/polarsys/capella/core/data/core/ui/quickfix/resolver/I_03_Resolver.java
  core/plugins/org.polarsys.capella.core.libraries.ui/src/org/polarsys/capella/core/libraries/ui/handlers/ManageReferencedLibrariesHandler.java
  core/plugins/org.polarsys.capella.core.libraries.ui/src/org/polarsys/capella/core/libraries/ui/views/libraryManager/referencesManager/ReferencesManagerWidget.java
  core/plugins/org.polarsys.capella.core.libraries/src/org/polarsys/capella/core/libraries/model/AbstractCapellaModel.java
  core/plugins/org.polarsys.capella.core.libraries/src/org/polarsys/capella/core/libraries/model/CapellaLibraryExt.java
  core/plugins/org.polarsys.capella.core.libraries/src/org/polarsys/capella/core/libraries/model/CapellaModel.java
  core/plugins/org.polarsys.capella.core.libraries/src/org/polarsys/capella/core/libraries/model/ModelIdentifier.java
  core/plugins/org.polarsys.capella.core.libraries/src/org/polarsys/capella/core/libraries/properties/LibraryManagerModel.java
  core/plugins/org.polarsys.capella.core.libraries/src/org/polarsys/capella/core/libraries/properties/ReferencesProperty.java
Labels: cherry-pick :cherries:, review-requested :lollipop:

#172 [releng] Add registered trademark and update about
  core/plugins/org.polarsys.capella.core.platform.sirius.ui.perspective/splash.bmp
  releng/plugins/org.polarsys.capella.rcp/icons/CapellaAbout.png
  releng/plugins/org.polarsys.capella.rcp/plugin.properties
Labels: review-requested :lollipop:

#227 Is cherry picks
  core/plugins/org.polarsys.capella.core.sirius.analysis/description/common.odesign
Labels: cherry-pick :cherries:

#194 [561365] Richtext can lost the last modification when switching tab
  core/plugins/org.polarsys.capella.core.ui.properties.richtext/src/org/polarsys/capella/core/ui/properties/richtext/fields/ElementDescriptionGroup.java
  core/plugins/org.polarsys.capella.core.ui.properties.richtext/src/org/polarsys/capella/core/ui/properties/richtext/sections/CapellaDescriptionPropertySection.java
  releng/plugins/org.polarsys.capella.targets/full/capella.target-definition.targetplatform
Labels: to: squash :cookie:

#216 [563327] In scenario initialization Guard are not referenced on operands
  core/plugins/org.polarsys.capella.core.projection.scenario/src/org/polarsys/capella/core/projection/scenario/uml2/rules/Rule_InteractionOperand.java
  tests/plugins/org.polarsys.capella.test.transition.ju/model/CreateRule_Scenario/CreateRule_Scenario.melodymodeller
  tests/plugins/org.polarsys.capella.test.transition.ju/src/org/polarsys/capella/test/transition/ju/transitions/CreateRule_ScenarioUml2_01.java
Labels: review-requested :lollipop:

#237 [558032] Display Title block as a tree and under its referenced element
  core/plugins/org.polarsys.capella.core.diagram.helpers/src/org/polarsys/capella/core/diagram/helpers/TitleBlockHelper.java
  core/plugins/org.polarsys.capella.core.sirius.analysis/icons/full/obj16/TitleBlockCell_16.gif
  core/plugins/org.polarsys.capella.core.sirius.analysis/src/org/polarsys/capella/core/sirius/analysis/providers/TitleBlockItemProvider.java
  core/plugins/org.polarsys.capella.core.sirius.analysis/src/org/polarsys/capella/core/sirius/analysis/providers/TitleBlockItemProviderDecorator.java
Labels: review-requested :lollipop:

#243 Fix Title Block CTRL + drag duplication bug
  core/plugins/org.polarsys.capella.core.diagram.helpers/src/org/polarsys/capella/core/diagram/helpers/TitleBlockHelper.java
  core/plugins/org.polarsys.capella.core.sirius.analysis/plugin.xml
  core/plugins/org.polarsys.capella.core.sirius.analysis/src/org/polarsys/capella/core/sirius/analysis/editpart/DDiagramEditPartProvider.java
Labels: review-requested :lollipop:
