Repository eclipse-capella/capella, pull requests merged in 2020-09, with the labels that each got.

#355 [566412] Fix junit regression from 566412 (wrong id)
  tests/plugins/org.polarsys.capella.test.transition.ju/src/org/polarsys/capella/test/transition/ju/common/SimpleResolver.java
  tests/plugins/org.polarsys.capella.test.transition.ju/src/org/polarsys/capella/test/transition/ju/transitions/CreateRule_ES2ES_01.java
Labels: review-requested :lollipop:

#353 [566538] Impossible to remove the state/modes of a Capability in a State Machine and Capability Function Matrix
  core/plugins/org.polarsys.capella.core.sirius.analysis/description/common.odesign
  tests/plugins/org.polarsys.capella.test.table/model/SF-OA/SF-OA.melodymodeller
  tests/plugins/org.polarsys.capella.test.table/src/org/polarsys/capella/test/table/ju/function/state/StateModeTableTestCase.java
  tests/plugins/org.polarsys.capella.test.table/src/org/polarsys/capella/test/table/ju/function/state/StateModeTableTestSuite.java
  tests/plugins/org.polarsys.capella.test.table/src/org/polarsys/capella/test/table/ju/function/state/TableStateModeFramework.java
  tests/plugins/org.polarsys.capella.test.table/src/org/polarsys/capella/test/table/ju/testsuite/TableTestSuite.java
Labels: build-unstable

#357 [566601] xFBD diagram on actor doesn't highlight function as blue
  core/plugins/org.polarsys.capella.core.sirius.analysis/description/context.odesign
  core/plugins/org.polarsys.capella.core.sirius.analysis/description/logical.odesign
  core/plugins/org.polarsys.capella.core.sirius.analysis/description/oa.odesign
  core/plugins/org.polarsys.capella.core.sirius.analysis/description/physical.odesign
  core/plugins/org.polarsys.capella.core.sirius.analysis/src/org/polarsys/capella/core/sirius/analysis/constants/ColorNameConstants.java
  tests/plugins/org.polarsys.capella.test.diagram.misc.ju/model/EOLE_AF_UC/EOLE_AF_UC.aird
  tests/plugins/org.polarsys.capella.test.diagram.misc.ju/src/org/polarsys/capella/test/diagram/misc/ju/testcases/ColorNameConstantsTest.java
  tests/plugins/org.polarsys.capella.test.diagram.misc.ju/src/org/polarsys/capella/test/diagram/misc/ju/testsuites/DiagramMiscTestSuite.java
  tests/plugins/org.polarsys.capella.test.diagram.tools.ju/src/org/polarsys/capella/test/diagram/tools/ju/testsuites/partial/XBDiagramToolsTestSuite.java
  tests/plugins/org.polarsys.capella.test.diagram.tools.ju/src/org/polarsys/capella/test/diagram/tools/ju/xfbd/XFBDBlueBold.java
  tests/plugins/org.polarsys.capella.test.framework/src/org/polarsys/capella/test/framework/helpers/SkeletonHelper.java
Labels: build-unstable, review-requested :lollipop:

#361 [Releng] Do not remove maven folders in the final product
  releng/plugins/org.polarsys.capella.rcp.product/pom.xml
Labels: build-unstable

#362 [Releng] Add the mistakenly removed zip steps
  releng/plugins/org.polarsys.capella.rcp.product/pom.xml
Labels: build-unstable

#365 [566828] Cannot open at once a selection of representations available in
  core/plugins/org.polarsys.capella.core.ui.semantic.browser.sirius/plugin.xml
  core/plugins/org.polarsys.capella.core.ui.semantic.browser.sirius/src/org/polarsys/capella/core/ui/semantic/browser/sirius/actions/DiagramOpenAction.java
  core/plugins/org.polarsys.capella.core.ui.semantic.browser.sirius/src/org/polarsys/capella/core/ui/semantic/browser/sirius/view/SiriusSemanticBrowserView.java
Labels: build-unstable

#367 [566940] Project Explorer icons are missing
  core/plugins/org.polarsys.capella.core.platform.sirius.ui.navigator/icons/QuickFiltersMenu.png
  core/plugins/org.polarsys.capella.core.platform.sirius.ui.navigator/icons/full/elcl16/collapseall.png
  core/plugins/org.polarsys.capella.core.platform.sirius.ui.navigator/icons/full/elcl16/license.txt
  core/plugins/org.polarsys.capella.core.platform.sirius.ui.navigator/icons/full/elcl16/synced.png
  core/plugins/org.polarsys.capella.core.platform.sirius.ui.navigator/icons/license.txt
Labels: build-unstable

#369 [566984] Remove mode/states from function in Capability Function and
  core/plugins/org.polarsys.capella.core.sirius.analysis/description/common.odesign
  core/plugins/org.polarsys.capella.core.sirius.analysis/src/org/polarsys/capella/core/sirius/analysis/IDiagramNameConstants.java
  tests/plugins/org.polarsys.capella.test.table/src/org/polarsys/capella/test/table/ju/state/StateModeTableTestCase.java
  tests/plugins/org.polarsys.capella.test.table/src/org/polarsys/capella/test/table/ju/state/StateModeTableTestSuite.java
  tests/plugins/org.polarsys.capella.test.table/src/org/polarsys/capella/test/table/ju/state/TableStateModeFramework.java
  tests/plugins/org.polarsys.capella.test.table/src/org/polarsys/capella/test/table/ju/state/contextual/ContextualStateModeTableTestSuite.java
  tests/plugins/org.polarsys.capella.test.table/src/org/polarsys/capella/test/table/ju/state/contextual/ModeTableTestCase.java
  tests/plugins/org.polarsys.capella.test.table/src/org/polarsys/capella/test/table/ju/state/contextual/StateTableTestCase.java
  tests/plugins/org.polarsys.capella.test.table/src/org/polarsys/capella/test/table/ju/state/contextual/TableContextualStateModeFramework.java
  tests/plugins/org.polarsys.capella.test.table/src/org/polarsys/capella/test/table/ju/testsuite/TableTestSuite.java
Labels: build-unstable

#368 [releng] Bundle openjdk-14.0.2 with Capella
  Jenkinsfile
  releng/plugins/org.polarsys.capella.rcp.product/pom.xml
Labels: build-unstable

#370 [doc] Update documentation in regards to embedded openjdk-14.0.2
  doc/plugins/org.polarsys.capella.ui.doc/.settings/org.eclipse.core.resources.prefs
  doc/plugins/org.polarsys.capella.ui.doc/html/Installation Guide/How to install Capella and Addons.html
  doc/plugins/org.polarsys.capella.ui.doc/html/Installation Guide/How to install Capella and Addons.mediawiki
  releng/plugins/org.polarsys.capella.rcp.product/pom.xml
Labels: build-unstable

#302 [releng][oomph] Update setup
  releng/plugins/org.polarsys.capella.settings/oomph/Capella.setup
Labels: build-unstable

#372 [566828] Cannot open at once a selection of representations available in Semantic Browser
  core/plugins/org.polarsys.capella.core.ui.semantic.browser.sirius/src/org/polarsys/capella/core/ui/semantic/browser/sirius/view/SiriusSemanticBrowserView.java
Labels: build-unstable
