Repository eclipse-capella/capella, pull requests merged in 2020-08, with the labels that each got.

#321 [565894] Actors stored under packages are not well managed in some cases
  core/plugins/org.polarsys.capella.core.model.helpers/src/org/polarsys/capella/core/model/helpers/queries/GetBrotherComponents.java
  core/plugins/org.polarsys.capella.core.sirius.analysis/description/common.odesign
  core/plugins/org.polarsys.capella.core.sirius.analysis/description/context.odesign
  core/plugins/org.polarsys.capella.core.sirius.analysis/description/logical.odesign
  core/plugins/org.polarsys.capella.core.sirius.analysis/description/physical.odesign
  core/plugins/org.polarsys.capella.core.sirius.analysis/src/org/polarsys/capella/core/sirius/analysis/CsServices.java
  core/plugins/org.polarsys.capella.core.sirius.analysis/src/org/polarsys/capella/core/sirius/analysis/queries/QueryIdentifierConstants.java
  tests/plugins/org.polarsys.capella.test.diagram.tools.ju/model/ContextualInterface/.project
  tests/plugins/org.polarsys.capella.test.diagram.tools.ju/model/ContextualInterface/ContextualInterface.afm
  tests/plugins/org.polarsys.capella.test.diagram.tools.ju/model/ContextualInterface/ContextualInterface.aird
  tests/plugins/org.polarsys.capella.test.diagram.tools.ju/model/ContextualInterface/ContextualInterface.melodymodeller
  tests/plugins/org.polarsys.capella.test.diagram.tools.ju/src/org/polarsys/capella/test/diagram/tools/ju/cei/ShowHideCEIActorQuery.java
  tests/plugins/org.polarsys.capella.test.diagram.tools.ju/src/org/polarsys/capella/test/diagram/tools/ju/cii/ShowHideCIIActorQuery.java
  tests/plugins/org.polarsys.capella.test.diagram.tools.ju/src/org/polarsys/capella/test/diagram/tools/ju/testsuites/main/DiagramToolsStep2TestSuite.java
  tests/plugins/org.polarsys.capella.test.diagram.tools.ju/src/org/polarsys/capella/test/diagram/tools/ju/testsuites/partial/ContextualInterfaceDiagramTestSuite.java
Labels: review-requested :lollipop:

#324 [566031] Semantic Browser in unsynchronized mode changes content in an
  core/plugins/org.polarsys.capella.core.ui.semantic.browser/src/org/polarsys/capella/core/ui/semantic/browser/view/SemanticBrowserView.java
  tests/plugins/org.polarsys.capella.test.diagram.misc.ju/src/org/polarsys/capella/test/diagram/misc/ju/testcases/UnsyncronizedSemanticBrowser.java
  tests/plugins/org.polarsys.capella.test.diagram.misc.ju/src/org/polarsys/capella/test/diagram/misc/ju/testsuites/DiagramMiscTestSuite.java
Labels: review-requested :lollipop:

#334 [566374] Deletion of Title Block prevent deletion of other elements
  core/plugins/org.polarsys.capella.core.sirius.analysis/META-INF/MANIFEST.MF
  core/plugins/org.polarsys.capella.core.sirius.analysis/src/org/polarsys/capella/core/sirius/analysis/providers/Messages.java
  core/plugins/org.polarsys.capella.core.sirius.analysis/src/org/polarsys/capella/core/sirius/analysis/providers/TitleBlockItemProvider.java
  core/plugins/org.polarsys.capella.core.sirius.analysis/src/org/polarsys/capella/core/sirius/analysis/providers/messages.properties
  tests/plugins/org.polarsys.capella.test.diagram.common.ju/src/org/polarsys/capella/test/diagram/common/ju/context/CommonDiagram.java
  tests/plugins/org.polarsys.capella.test.diagram.common.ju/src/org/polarsys/capella/test/diagram/common/ju/step/tools/DeleteElementTool.java
  tests/plugins/org.polarsys.capella.test.diagram.common.ju/src/org/polarsys/capella/test/diagram/common/ju/step/tools/titleblocks/DeleteTitleBlockTool.java
  tests/plugins/org.polarsys.capella.test.diagram.tools.ju/src/org/polarsys/capella/test/diagram/tools/ju/tb/AbstractTitleBlockTestCase.java
  tests/plugins/org.polarsys.capella.test.diagram.tools.ju/src/org/polarsys/capella/test/diagram/tools/ju/tb/CDBTitleBlockTestCase.java
  tests/plugins/org.polarsys.capella.test.diagram.tools.ju/src/org/polarsys/capella/test/diagram/tools/ju/xab/DeleteConstraintLink.java
Labels: review-requested :lollipop:

#327 [566245] Validation rules I_40 and DCOV_07 are disabled in some models
  core/plugins/org.polarsys.capella.core.data.core.validation/src/org/polarsys/capella/core/data/core/validation/constraint/UniqueInvolvementConstraint.java
  core/plugins/org.polarsys.capella.core.data.helpers/src/org/polarsys/capella/core/data/helpers/ctx/services/CapabilityExt.java
  core/plugins/org.polarsys.capella.core.model.helpers/src/org/polarsys/capella/core/model/helpers/CapabilityRealizationExt.java
  tests/plugins/org.polarsys.capella.test.model.ju/model/capabilityExt/.project
  tests/plugins/org.polarsys.capella.test.model.ju/model/capabilityExt/capabilityExt.afm
  tests/plugins/org.polarsys.capella.test.model.ju/model/capabilityExt/capabilityExt.aird
  tests/plugins/org.polarsys.capella.test.model.ju/model/capabilityExt/capabilityExt.melodymodeller
  tests/plugins/org.polarsys.capella.test.model.ju/src/org/polarsys/capella/test/model/ju/helpers/CapabilityExtTestCase.java
  tests/plugins/org.polarsys.capella.test.validation.rules.ju/model/RulesOnDesignTest/RulesOnDesignTest.melodymodeller
  tests/plugins/org.polarsys.capella.test.validation.rules.ju/model/RulesOnIntegrityTest/RulesOnIntegrityTest.melodymodeller
  tests/plugins/org.polarsys.capella.test.validation.rules.ju/src/org/polarsys/capella/test/validation/rules/ju/testcases/dcov/Rule_DCOV_07.java
  tests/plugins/org.polarsys.capella.test.validation.rules.ju/src/org/polarsys/capella/test/validation/rules/ju/testcases/i/Rule_I_40_OnCapability.java
Labels: review-requested :lollipop:, to: rebase-and-merge :doughnut:

#346 [566412] Fix junit regression from 566412
  tests/plugins/org.polarsys.capella.test.transition.ju/src/org/polarsys/capella/test/transition/ju/common/SimpleResolver.java
  tests/plugins/org.polarsys.capella.test.transition.ju/src/org/polarsys/capella/test/transition/ju/transitions/CreateRule_ES2ES_01.java
Labels: review-requested :lollipop:

#350 [releng] Update Sirius version to the 6.3.3 release
  releng/plugins/org.polarsys.capella.settings/oomph/Capella.setup
  releng/plugins/org.polarsys.capella.targets/full/capella.target-definition.targetplatform
Labels: review-requested :lollipop:

#349 [releng] Add dynamic pull request labels for current build status
  Jenkinsfile
Labels: build-unstable

#351 [sonar] Fix blocking issues on Sonar
  common/plugins/org.polarsys.capella.common.tools.report.appenders.reportlogview/src/org/polarsys/capella/common/tools/report/appenders/reportlogview/handler/SaveLogHandler.java
  core/plugins/org.polarsys.capella.core.data.core.properties/src/org/polarsys/capella/core/data/core/properties/sections/DiagramTitleBlockContainerSection.java
  core/plugins/org.polarsys.capella.core.data.core.properties/src/org/polarsys/capella/core/data/core/properties/sections/ElementTitleBlockContainerSection.java
  core/plugins/org.polarsys.capella.core.data.cs.ui.quickfix/src/org/polarsys/capella/core/data/cs/ui/quickfix/resolver/SwitchIsActorIsHumanFlag_Resolver.java
  core/plugins/org.polarsys.capella.core.data.fa.ui.quickfix/src/org/polarsys/capella/core/data/fa/ui/quickfix/resolver/DWF_DF_16_Resolver.java
  core/plugins/org.polarsys.capella.core.data.fa.ui.quickfix/src/org/polarsys/capella/core/data/fa/ui/quickfix/resolver/DWF_DF_18_Resolver.java
  core/plugins/org.polarsys.capella.core.data.fa.ui.quickfix/src/org/polarsys/capella/core/data/fa/ui/quickfix/resolver/RemoveSequenceLinksAssociationsResolver.java
  core/plugins/org.polarsys.capella.core.data.helpers/src/org/polarsys/capella/core/data/helpers/fa/services/BusPatternHelper.java
  core/plugins/org.polarsys.capella.core.data.interaction.ui.quickfix/src/org/polarsys/capella/core/data/interaction/ui/quickfix/resolver/AddInvolvedElementsResolver.java
  core/plugins/org.polarsys.capella.core.data.pa.ui.quickfix/src/org/polarsys/capella/core/data/pa/ui/quickfix/resolver/PhysicalComponentNatureToBehaviorResolver.java
  core/plugins/org.polarsys.capella.core.data.pa.ui.quickfix/src/org/polarsys/capella/core/data/pa/ui/quickfix/resolver/PhysicalComponentNatureToNodeResolver.java
  core/plugins/org.polarsys.capella.core.libraries.ui/src/org/polarsys/capella/core/libraries/ui/views/libraryManager/accessPolicyManager/AccessPolicyLabelProvider.java
  core/plugins/org.polarsys.capella.core.model.helpers/src/org/polarsys/capella/core/model/utils/saxparser/WriteCapellaElementDescriptionSAXParser.java
  core/plugins/org.polarsys.capella.core.platform.sirius.sirius.validation/src/org/polarsys/capella/core/platform/sirius/sirius/validation/ddiagram/CapellaElementInDescriptionExistanceCheck.java
  core/plugins/org.polarsys.capella.core.platform.sirius.sirius.validation/src/org/polarsys/capella/core/platform/sirius/sirius/validation/ddiagram/CapellaElementInDescriptionNameCheck.java
  core/plugins/org.polarsys.capella.core.platform.sirius.sirius.validation/src/org/polarsys/capella/core/platform/sirius/sirius/validation/ddiagram/DeleteInValidHyperLinkInDescription.java
  core/plugins/org.polarsys.capella.core.preferences.project.configuration/src/org/polarsys/capella/core/preferences/trasferers/WizardPreferencesTransfererExportPage.java
  core/plugins/org.polarsys.capella.core.preferences/src/org/polarsys/capella/core/preferences/transferer/WizardPreferencesTransfererExportPage.java
  core/plugins/org.polarsys.capella.core.sirius.analysis/src/org/polarsys/capella/core/sirius/analysis/TitleBlockServices.java
  core/plugins/org.polarsys.capella.core.transition.diagram/src/org/polarsys/capella/core/transition/diagram/handlers/CapabilitiesHandler.java
  core/plugins/org.polarsys.capella.core.validation.ui/src/org/polarsys/capella/core/validation/ui/actions/EPFValidationAction.java
  ext/detachment/plugins/org.polarsys.capella.detachment.version.precondition/src/org/polarsys/capella/detachment/version/precondition/impl/VersionChecker.java
Labels: review-requested :lollipop:
