Repository eclipse-capella/capella, pull requests merged in 2021-03, with the labels that each got.

#2111 #2038 Final States in State Machine raise DWF_SM_16
  core/plugins/org.polarsys.capella.core.data.common.validation/src/org/polarsys/capella/core/data/common/validation/statetransition/MDCHK_State_Mode_Siblings.java
  tests/plugins/org.polarsys.capella.test.validation.rules.ju/model/RulesOnDesignTest/RulesOnDesignTest.capella
  tests/plugins/org.polarsys.capella.test.validation.rules.ju/src/org/polarsys/capella/test/validation/rules/ju/testcases/dwf_sm/Rule_DWF_SM_16.java
Labels: build-unstable

#2120 #2119 Add Capella feature on About Dialog
  releng/plugins/org.polarsys.capella.rcp/about.ini
Labels: build-unstable

#2117 #2116 Add missing menus on SemanticBrowser and Interpreter
  core/plugins/org.polarsys.capella.core.platform.sirius.ui.actions/META-INF/MANIFEST.MF
  core/plugins/org.polarsys.capella.core.platform.sirius.ui.actions/plugin.properties
  core/plugins/org.polarsys.capella.core.platform.sirius.ui.actions/plugin.xml
  core/plugins/org.polarsys.capella.core.platform.sirius.ui.actions/src/org/polarsys/capella/core/platform/sirius/ui/handlers/DeleteHandler.java
  core/plugins/org.polarsys.capella.core.platform.sirius.ui.menu/plugin.properties
  core/plugins/org.polarsys.capella.core.platform.sirius.ui.menu/plugin.xml
  core/plugins/org.polarsys.capella.core.platform.sirius.ui.navigator/META-INF/MANIFEST.MF
  core/plugins/org.polarsys.capella.core.platform.sirius.ui.navigator/plugin.xml
  core/plugins/org.polarsys.capella.core.platform.sirius.ui.navigator/src/org/polarsys/capella/core/platform/sirius/ui/navigator/actions/providers/DynamicNewRepresentationContributionItem.java
  core/plugins/org.polarsys.capella.core.platform.sirius.ui.navigator/src/org/polarsys/capella/core/platform/sirius/ui/navigator/actions/providers/DynamicOpenRepresentationContributionItem.java
  core/plugins/org.polarsys.capella.core.platform.sirius.ui.navigator/src/org/polarsys/capella/core/platform/sirius/ui/navigator/actions/providers/NewRepresentationActionProvider.java
  core/plugins/org.polarsys.capella.core.platform.sirius.ui.navigator/src/org/polarsys/capella/core/platform/sirius/ui/navigator/actions/providers/OpenRepresentationActionProvider.java
  core/plugins/org.polarsys.capella.core.sirius.ui/plugin.xml
  core/plugins/org.polarsys.capella.core.ui.properties.richtext/META-INF/MANIFEST.MF
  core/plugins/org.polarsys.capella.core.ui.properties.richtext/plugin.xml
  core/plugins/org.polarsys.capella.core.ui.semantic.browser.sirius/plugin.xml
  doc/plugins/org.polarsys.capella.ui.doc/html/04. User Interface/4.07. Semantic Browser.html
  doc/plugins/org.polarsys.capella.ui.doc/html/04. User Interface/4.07. Semantic Browser.mediawiki
  doc/plugins/org.polarsys.capella.ui.doc/html/04. User Interface/Images/4.07. Semantic Browser_html_m7ad4cfca.png
  doc/plugins/org.polarsys.capella.ui.doc/html/04. User Interface/Images/4.07_Semantic_Browser.png
  tests/plugins/org.polarsys.capella.test.model.ju/META-INF/MANIFEST.MF
  tests/plugins/org.polarsys.capella.test.model.ju/src/org/polarsys/capella/test/model/ju/menu/CapellaMenusTestCase.java
  tests/plugins/org.polarsys.capella.test.model.ju/src/org/polarsys/capella/test/model/ju/testsuites/main/ModelTestSuite.java
Labels: build-successfull

#2100 #2094 Fix Accelerator tool to create PL on Actor
  core/plugins/org.polarsys.capella.core.data.business.queries/src/org/polarsys/capella/core/business/queries/queries/cs/GetAvailable_PhysicalLink_AllocatedComponentExchanges.java
  core/plugins/org.polarsys.capella.core.model.helpers/src/org/polarsys/capella/core/model/helpers/PhysicalLinkExt.java
  core/plugins/org.polarsys.capella.core.projection.exchanges/META-INF/MANIFEST.MF
  core/plugins/org.polarsys.capella.core.projection.exchanges/src/org/polarsys/capella/core/projection/exchanges/ConnectionCreatorFactory.java
  core/plugins/org.polarsys.capella.core.projection.exchanges/src/org/polarsys/capella/core/projection/exchanges/LinkCreatorFactory.java
  core/plugins/org.polarsys.capella.core.projection.exchanges/src/org/polarsys/capella/core/projection/exchanges/NodePhysicalComponentExchangesCreator.java
  core/plugins/org.polarsys.capella.core.projection.exchanges/src/org/polarsys/capella/core/projection/exchanges/PhysicalActorExchangesCreator.java
  core/plugins/org.polarsys.capella.core.projection.exchanges/src/org/polarsys/capella/core/projection/exchanges/PhysicalLinksCreator.java
  core/plugins/org.polarsys.capella.core.sirius.analysis/description/context.odesign
  core/plugins/org.polarsys.capella.core.sirius.analysis/description/logical.odesign
  core/plugins/org.polarsys.capella.core.sirius.analysis/src/org/polarsys/capella/core/sirius/analysis/ABServices.java
  tests/plugins/org.polarsys.capella.test.model.ju/META-INF/MANIFEST.MF
  tests/plugins/org.polarsys.capella.test.model.ju/model/miscmodel/miscmodel.aird
  tests/plugins/org.polarsys.capella.test.model.ju/model/miscmodel/miscmodel.capella
  tests/plugins/org.polarsys.capella.test.model.ju/src/org/polarsys/capella/test/model/ju/accelerators/PhysicalLinkAcceleratorTest.java
  tests/plugins/org.polarsys.capella.test.model.ju/src/org/polarsys/capella/test/model/ju/helpers/ComponentPkgExtTestCase.java
  tests/plugins/org.polarsys.capella.test.model.ju/src/org/polarsys/capella/test/model/ju/model/MiscModel.java
  tests/plugins/org.polarsys.capella.test.model.ju/src/org/polarsys/capella/test/model/ju/testsuites/main/ModelTestSuite.java
Labels: build-unstable

#2130 #2116 Fix delete binding conflict for Resources and Model Elements
  core/plugins/org.polarsys.capella.core.platform.sirius.ui.actions/plugin.xml
  core/plugins/org.polarsys.capella.core.platform.sirius.ui.actions/src/org/polarsys/capella/core/platform/sirius/ui/handlers/DeleteHandler.java
  core/plugins/org.polarsys.capella.core.ui.semantic.browser/plugin.properties
  core/plugins/org.polarsys.capella.core.ui.semantic.browser/plugin.xml
  core/plugins/org.polarsys.capella.core.ui.semantic.browser/src/org/polarsys/capella/core/ui/semantic/browser/view/SemanticBrowserView.java
Labels: build-unstable

#2129 #2128 Fix Copy as text for CategoryWrapper and PrimitiveWrapper
  common/plugins/org.polarsys.capella.common.ui.toolkit.browser/src/org/polarsys/capella/common/ui/toolkit/browser/content/provider/wrapper/CategoryWrapper.java
  common/plugins/org.polarsys.capella.common.ui.toolkit.browser/src/org/polarsys/capella/common/ui/toolkit/browser/content/provider/wrapper/PrimitiveWrapper.java
  core/plugins/org.polarsys.capella.core.sirius.ui/src/org/polarsys/capella/core/sirius/ui/handlers/CopyTextHandler.java
  tests/plugins/org.polarsys.capella.test.model.ju/src/org/polarsys/capella/test/model/ju/menu/CapellaMenusTestCase.java
Labels: build-unstable

#2132 #2131 Delete Wizard improved displaying all impacted elements by default
  core/plugins/org.polarsys.capella.core.ui.toolkit/src/org/polarsys/capella/core/ui/toolkit/dialogs/ConfirmDeleteCapellaElementDialog.java
  tests/plugins/org.polarsys.capella.test.model.ju/src/org/polarsys/capella/test/model/ju/testcases/delete/DeleteElementTestSuite.java
  tests/plugins/org.polarsys.capella.test.model.ju/src/org/polarsys/capella/test/model/ju/testcases/delete/DeleteShowReferencingImpact.java
  tests/plugins/org.polarsys.capella.test.model.ju/src/org/polarsys/capella/test/model/ju/testcases/delete/DeleteTest.java
Labels: build-unstable

#2124 #2116 Add missing menus "Validate Model" on SemanticBrowser
  common/plugins/org.polarsys.capella.common.ui.massactions/plugin.xml
  core/plugins/org.polarsys.capella.core.data.core.validation/plugin.xml
  core/plugins/org.polarsys.capella.core.libraries.ui/plugin.xml
  core/plugins/org.polarsys.capella.core.platform.sirius.ui.actions/plugin.xml
  core/plugins/org.polarsys.capella.core.platform.sirius.ui.actions/src/org/polarsys/capella/core/platform/sirius/ui/handlers/DeleteHandler.java
  core/plugins/org.polarsys.capella.core.validation.ui/plugin.xml
  core/plugins/org.polarsys.capella.core.validation.ui/src/org/polarsys/capella/core/validation/ui/DynamicActionProvider.java
  core/plugins/org.polarsys.capella.core.validation.ui/src/org/polarsys/capella/core/validation/ui/DynamicCreateContributionItem.java
  core/plugins/org.polarsys.capella.core.validation.ui/src/org/polarsys/capella/core/validation/ui/actions/ValidationActionProvider.java
  doc/plugins/org.polarsys.capella.ui.doc/html/04. User Interface/Images/4.07_Semantic_Browser.png
Labels: build-unstable

#2110 #2109 Notification on DAnnotation should refresh its representation
  core/plugins/org.polarsys.capella.core.sirius.ui/plugin.xml
  core/plugins/org.polarsys.capella.core.sirius.ui/src/org/polarsys/capella/core/sirius/ui/listener/DAnnotationChangeTrigger.java
  core/plugins/org.polarsys.capella.core.sirius.ui/src/org/polarsys/capella/core/sirius/ui/listener/DAnnotationPrecommitListener.java
  tests/plugins/org.polarsys.capella.test.diagram.misc.ju/src/org/polarsys/capella/test/diagram/misc/ju/testcases/DAnnotationChangeTest.java
Labels: build-unstable

#2134 #2133 Component Port Allocation is not visible in diagram LAB
  core/plugins/org.polarsys.capella.core.model.helpers/src/org/polarsys/capella/core/model/helpers/PhysicalLinkExt.java
  core/plugins/org.polarsys.capella.core.projection.exchanges/src/org/polarsys/capella/core/projection/exchanges/PhysicalLinksCreator.java
  tests/plugins/org.polarsys.capella.test.model.ju/model/miscmodel/miscmodel.aird
  tests/plugins/org.polarsys.capella.test.model.ju/model/miscmodel/miscmodel.capella
  tests/plugins/org.polarsys.capella.test.model.ju/src/org/polarsys/capella/test/model/ju/accelerators/PhysicalLinkAcceleratorTest.java
  tests/plugins/org.polarsys.capella.test.model.ju/src/org/polarsys/capella/test/model/ju/helpers/ComponentPkgExtTestCase.java
  tests/plugins/org.polarsys.capella.test.model.ju/src/org/polarsys/capella/test/model/ju/model/MiscModel.java
Labels: build-unstable

#2141 #2140 Sorted Architecture in transferviewer
  common/plugins/org.polarsys.capella.common.ui/src/org/polarsys/capella/common/ui/toolkit/viewers/TreeAndListViewer.java
  common/plugins/org.polarsys.capella.common.ui/src/org/polarsys/capella/common/ui/toolkit/viewers/data/AbstractData.java
  common/plugins/org.polarsys.capella.common.ui/src/org/polarsys/capella/common/ui/toolkit/viewers/data/TreeData.java
  tests/plugins/org.polarsys.capella.test.model.ju/src/org/polarsys/capella/test/model/ju/dialog/CapellaTreeDataTestCase.java
  tests/plugins/org.polarsys.capella.test.model.ju/src/org/polarsys/capella/test/model/ju/testsuites/main/ModelTestSuite.java
Labels: build-unstable

#2144 #2143 Remove NewLine on using CopyAs command
  core/plugins/org.polarsys.capella.core.sirius.ui/src/org/polarsys/capella/core/sirius/ui/handlers/CopyTextHandler.java
  tests/plugins/org.polarsys.capella.test.model.ju/src/org/polarsys/capella/test/model/ju/menu/CapellaMenusTestCase.java
Labels: build-unstable

#2098 #2092 Add documentation about displaying multi-branch physical path
  doc/plugins/org.polarsys.capella.ui.doc/html/05. Diagram Management/5.5. Creation of Functional Chains and Physical Paths.html
  doc/plugins/org.polarsys.capella.ui.doc/html/05. Diagram Management/5.5. Creation of Functional Chains and Physical Paths.mediawiki
  doc/plugins/org.polarsys.capella.ui.doc/html/05. Diagram Management/Images/MultibranchPP.png
  doc/plugins/org.polarsys.capella.ui.doc/html/05. Diagram Management/Images/MultibranchPPDisplay.png
  doc/plugins/org.polarsys.capella.ui.doc/html/05. Diagram Management/Images/PPInternalLinkFilter.png
  doc/plugins/org.polarsys.capella.ui.doc/license.txt
Labels: build-unstable

#2137 [test] Fix PropertyViewTest
  tests/plugins/org.polarsys.capella.test.model.ju/META-INF/MANIFEST.MF
  tests/plugins/org.polarsys.capella.test.model.ju/src/org/polarsys/capella/test/model/ju/propertyviews/PropertyViewsTest.java
Labels: build-unstable, review-requested :lollipop:

#2145 [releng] Update Sirius version to 6.5.0-S20210326-125830
  releng/plugins/org.polarsys.capella.settings/oomph/Capella.setup
  releng/plugins/org.polarsys.capella.targets/full/capella.target-definition.targetplatform
Labels: build-unstable

#2139 #2138 Issues with opening session while the model is in conflict state when working with Git
  core/plugins/org.polarsys.capella.core.platform.sirius.ui.actions/META-INF/MANIFEST.MF
  core/plugins/org.polarsys.capella.core.platform.sirius.ui.actions/plugin.xml
  core/plugins/org.polarsys.capella.core.platform.sirius.ui.actions/src/org/polarsys/capella/core/platform/sirius/ui/session/GitConflictHelper.java
  core/plugins/org.polarsys.capella.core.platform.sirius.ui.actions/src/org/polarsys/capella/core/platform/sirius/ui/session/GitReloadingPolicy.java
  core/plugins/org.polarsys.capella.core.platform.sirius.ui.actions/src/org/polarsys/capella/core/platform/sirius/ui/session/Messages.java
  core/plugins/org.polarsys.capella.core.platform.sirius.ui.actions/src/org/polarsys/capella/core/platform/sirius/ui/session/messages.properties
  core/plugins/org.polarsys.capella.core.platform.sirius.ui.navigator/src/org/polarsys/capella/core/platform/sirius/ui/navigator/viewer/CapellaUISession.java
  core/plugins/org.polarsys.capella.core.sirius.ui/src/org/polarsys/capella/core/sirius/ui/actions/OpenSessionAction.java
  doc/plugins/org.polarsys.capella.git.doc/html/GitAdapter/GitAdapter.html
  doc/plugins/org.polarsys.capella.git.doc/html/GitAdapter/GitAdapter.mediawiki
  doc/plugins/org.polarsys.capella.git.doc/html/GitAdapter/images/Flag.jpg
Labels: build-unstable, review-requested :lollipop:

#2115 #2045 Remove duplicated code on Capella
  core/plugins/org.polarsys.capella.core.sirius.ui/src/org/polarsys/capella/core/sirius/ui/handlers/RefreshDiagramsCommandHandler.java
  core/plugins/org.polarsys.capella.core.sirius.ui/src/org/polarsys/capella/core/sirius/ui/helper/SessionHelper.java
  tests/plugins/org.polarsys.capella.test.diagram.tools.ju/src/org/polarsys/capella/test/diagram/tools/ju/diagram/actions/RefreshAllOnDisabledProject.java
  tests/plugins/org.polarsys.capella.test.diagram.tools.ju/src/org/polarsys/capella/test/diagram/tools/ju/diagram/actions/RefreshAllOnNonCustomizedProject.java
  tests/plugins/org.polarsys.capella.test.diagram.tools.ju/src/org/polarsys/capella/test/diagram/tools/ju/diagram/actions/SpecificSettings.java
Labels: build-unstable, review-requested :lollipop:

#2136 #2135 Creation of Constraint link not possible for certain elements
  core/plugins/org.polarsys.capella.core.sirius.analysis/description/common.odesign
  tests/plugins/org.polarsys.capella.test.diagram.tools.ju/model/DiagramToolsModel/DiagramToolsModel.aird
  tests/plugins/org.polarsys.capella.test.diagram.tools.ju/model/DiagramToolsModel/DiagramToolsModel.capella
  tests/plugins/org.polarsys.capella.test.diagram.tools.ju/model/XABDiagrams/XABDiagrams.aird
  tests/plugins/org.polarsys.capella.test.diagram.tools.ju/model/XABDiagrams/XABDiagrams.capella
  tests/plugins/org.polarsys.capella.test.diagram.tools.ju/src/org/polarsys/capella/test/diagram/tools/ju/model/DiagramToolsModel.java
  tests/plugins/org.polarsys.capella.test.diagram.tools.ju/src/org/polarsys/capella/test/diagram/tools/ju/sequence/CreateConstrainedElement.java
  tests/plugins/org.polarsys.capella.test.diagram.tools.ju/src/org/polarsys/capella/test/diagram/tools/ju/testsuites/partial/SequenceDiagramToolsTestSuite.java
  tests/plugins/org.polarsys.capella.test.diagram.tools.ju/src/org/polarsys/capella/test/diagram/tools/ju/xab/CreateConstraintElement.java
  tests/plugins/org.polarsys.capella.test.diagram.tools.ju/src/org/polarsys/capella/test/diagram/tools/ju/xab/XABDiagramsProject.java
Labels: build-unstable

#2118 [releng] Update Capella target platform for IT1
  releng/plugins/org.polarsys.capella.targets/full/capella.target-definition.targetplatform
Labels: build-successfull

#2152 #2151 Validate and Copy as text menus are visible on empty selection
  core/plugins/org.polarsys.capella.core.sirius.ui/plugin.xml
  core/plugins/org.polarsys.capella.core.sirius.ui/src/org/polarsys/capella/core/sirius/ui/handlers/CopyTextHandler.java
  core/plugins/org.polarsys.capella.core.validation.ui/plugin.xml
  tests/plugins/org.polarsys.capella.test.model.ju/src/org/polarsys/capella/test/model/ju/menu/CapellaMenusTestCase.java
Labels: build-successfull

#2150 #2149 Realized information source isn't set on DataType from properties
  core/plugins/org.polarsys.capella.core.data.helpers/src/org/polarsys/capella/core/data/helpers/information/services/DataTypeExt.java
  tests/plugins/org.polarsys.capella.test.model.ju/model/miscmodel/miscmodel.aird
  tests/plugins/org.polarsys.capella.test.model.ju/model/miscmodel/miscmodel.capella
  tests/plugins/org.polarsys.capella.test.model.ju/src/org/polarsys/capella/test/model/ju/helpers/DataTypeRealizedInformationTest.java
  tests/plugins/org.polarsys.capella.test.model.ju/src/org/polarsys/capella/test/model/ju/testsuites/main/ModelTestSuite.java
Labels: build-successfull
