Repository eclipse-capella/capella, pull requests merged in 2021-05, with the labels that each got.

#2192 [releng] Update Sirius version to 6.5.0-S20210430-052046
  releng/plugins/org.polarsys.capella.settings/oomph/Capella.setup
  releng/plugins/org.polarsys.capella.targets/full/capella.target-definition.targetplatform
Labels: build-successfull

#453 [test] Add junits for Representations references in Semantic Browser
  tests/plugins/org.polarsys.capella.test.semantic.queries.ju/model/SemanticQueries/SemanticQueries.aird
  tests/plugins/org.polarsys.capella.test.semantic.queries.ju/src/org/polarsys/capella/test/semantic/queries/ju/model/SemanticQueries.java
  tests/plugins/org.polarsys.capella.test.semantic.queries.ju/src/org/polarsys/capella/test/semantic/queries/ju/testcases/AllRelatedDiagrams.java
  tests/plugins/org.polarsys.capella.test.semantic.queries.ju/src/org/polarsys/capella/test/semantic/queries/ju/testcases/AllRelatedTables.java
  tests/plugins/org.polarsys.capella.test.semantic.queries.ju/src/org/polarsys/capella/test/semantic/queries/ju/testcases/ContextualElements.java
  tests/plugins/org.polarsys.capella.test.semantic.queries.ju/src/org/polarsys/capella/test/semantic/queries/ju/testcases/ElementOfInterestOfRepresentations.java
  tests/plugins/org.polarsys.capella.test.semantic.queries.ju/src/org/polarsys/capella/test/semantic/queries/ju/testcases/ElementOfInterests.java
  tests/plugins/org.polarsys.capella.test.semantic.queries.ju/src/org/polarsys/capella/test/semantic/queries/ju/testsuites/SemanticQueriesTestSuite.java
Labels: build-successfull, review-requested :lollipop:

#2196 [releng] Update Sirius version to 6.5.0 RC2 (respin of Sirius IT3)
  releng/plugins/org.polarsys.capella.settings/oomph/Capella.setup
  releng/plugins/org.polarsys.capella.targets/full/capella.target-definition.targetplatform
Labels: build-successfull

#331 Ensure that DAnalysisSelector is CapellaDAnalysisSelector
  tests/plugins/org.polarsys.capella.test.diagram.common.ju/plugin.xml
  tests/plugins/org.polarsys.capella.test.diagram.common.ju/src/org/polarsys/capella/test/diagram/common/ju/headless/selector/HeadlessCapellaAnalysisSelector.java
  tests/plugins/org.polarsys.capella.test.diagram.common.ju/src/org/polarsys/capella/test/diagram/common/ju/headless/selector/TestSessionManagerListener.java
  tests/plugins/org.polarsys.capella.test.diagram.common.ju/src/org/polarsys/capella/test/diagram/common/ju/step/crud/CreateDTableStep.java
  tests/plugins/org.polarsys.capella.test.diagram.common.ju/src/org/polarsys/capella/test/diagram/common/ju/step/crud/CreateDiagramStep.java
  tests/plugins/org.polarsys.capella.test.diagram.misc.ju/src/org/polarsys/capella/test/diagram/misc/ju/testcases/CloneDiagramTestCase.java
  tests/plugins/org.polarsys.capella.test.platform.ju/src/org/polarsys/capella/test/platform/ju/testcases/CustomDAnalysisSelection.java
  tests/plugins/org.polarsys.capella.test.platform.ju/src/org/polarsys/capella/test/platform/ju/testsuites/PlatformTestSuite.java
Labels: build-successfull

#2198 [releng] Update Diffmerge 0.13.1-M3 and Kitalpha IT3
  releng/plugins/org.polarsys.capella.settings/oomph/Capella.setup
  releng/plugins/org.polarsys.capella.targets/full/capella.target-definition.targetplatform
Labels: build-started

#2200 [test] RCPTT test for Trace Manager Wizard
  tests/plugins/org.polarsys.capella.test.rcptt/AllTests.suite
  tests/plugins/org.polarsys.capella.test.rcptt/TraceElements/TraceElements.suite
  tests/plugins/org.polarsys.capella.test.rcptt/TraceElements/TraceManagerWizard.test
Labels: build-successfull
