Repository eclipse-capella/capella, pull requests merged in 2021-02, with the labels that each got.

#2060 #2041 Constraints
  core/plugins/org.polarsys.capella.core.semantic.queries/META-INF/MANIFEST.MF
  core/plugins/org.polarsys.capella.core.semantic.queries/src/org/polarsys/capella/core/semantic/queries/basic/queries/ConstraintModelElements.java
  core/plugins/org.polarsys.capella.core.sirius.analysis/description/context.odesign
  core/plugins/org.polarsys.capella.core.sirius.analysis/description/logical.odesign
  core/plugins/org.polarsys.capella.core.sirius.analysis/description/physical.odesign
  core/plugins/org.polarsys.capella.core.sirius.analysis/src/org/polarsys/capella/core/sirius/analysis/CsServices.java
Labels: build-aborted, build-unstable

#2056 #2055 The transition should include in its scope state/mode's do activities, entries, exits involving functions or exchange items
  core/plugins/org.polarsys.capella.core.transition.system.topdown/src/org/polarsys/capella/core/transition/system/topdown/rules/common/AbstractStateRule.java
  core/plugins/org.polarsys.capella.core.transition.system/src/org/polarsys/capella/core/transition/system/rules/common/AbstractStateRule.java
  tests/plugins/org.polarsys.capella.test.transition.ju/model/Context_I01/Context_I01.aird
  tests/plugins/org.polarsys.capella.test.transition.ju/model/Context_I01/Context_I01.capella
  tests/plugins/org.polarsys.capella.test.transition.ju/src/org/polarsys/capella/test/transition/ju/transitions/Context_SM01_03.java
Labels: build-unstable

#2074 #2073 [Semantic Browser] Add SB queries for Realized and Realizing State Transition
  core/plugins/org.polarsys.capella.core.semantic.queries/plugin.xml
  core/plugins/org.polarsys.capella.core.semantic.queries/src/org/polarsys/capella/core/semantic/queries/basic/queries/StateTransition_RealizedStateTransition.java
  core/plugins/org.polarsys.capella.core.semantic.queries/src/org/polarsys/capella/core/semantic/queries/basic/queries/StateTransition_RealizingStateTransition.java
  tests/plugins/org.polarsys.capella.test.semantic.queries.ju/model/SemanticQueries/SemanticQueries.aird
  tests/plugins/org.polarsys.capella.test.semantic.queries.ju/model/SemanticQueries/SemanticQueries.capella
  tests/plugins/org.polarsys.capella.test.semantic.queries.ju/src/org/polarsys/capella/test/semantic/queries/ju/model/SemanticQueries.java
  tests/plugins/org.polarsys.capella.test.semantic.queries.ju/src/org/polarsys/capella/test/semantic/queries/ju/testcases/StateTransition_realizedStateTransition.java
  tests/plugins/org.polarsys.capella.test.semantic.queries.ju/src/org/polarsys/capella/test/semantic/queries/ju/testcases/StateTransition_realizingStateTransition.java
  tests/plugins/org.polarsys.capella.test.semantic.queries.ju/src/org/polarsys/capella/test/semantic/queries/ju/testsuites/SemanticQueriesTestSuite.java
Labels: build-unstable

#2078 #2065 Show label icons with colors of overlapped physical paths / functional chains
  core/plugins/org.polarsys.capella.core.sirius.analysis/description/context.odesign
  core/plugins/org.polarsys.capella.core.sirius.analysis/description/logical.odesign
  core/plugins/org.polarsys.capella.core.sirius.analysis/description/oa.odesign
  core/plugins/org.polarsys.capella.core.sirius.analysis/description/physical.odesign
  core/plugins/org.polarsys.capella.core.sirius.analysis/plugin.properties
  core/plugins/org.polarsys.capella.core.sirius.analysis/plugin.xml
  core/plugins/org.polarsys.capella.core.sirius.analysis/src/org/polarsys/capella/core/sirius/analysis/DiagramServices.java
  core/plugins/org.polarsys.capella.core.sirius.analysis/src/org/polarsys/capella/core/sirius/analysis/FaServices.java
  core/plugins/org.polarsys.capella.core.sirius.analysis/src/org/polarsys/capella/core/sirius/analysis/FunctionalChainServices.java
  core/plugins/org.polarsys.capella.core.sirius.analysis/src/org/polarsys/capella/core/sirius/analysis/IMappingNameConstants.java
  core/plugins/org.polarsys.capella.core.sirius.analysis/src/org/polarsys/capella/core/sirius/analysis/PhysicalServices.java
  core/plugins/org.polarsys.capella.core.sirius.analysis/src/org/polarsys/capella/core/sirius/analysis/cache/DEdgeIconCache.java
  core/plugins/org.polarsys.capella.core.sirius.analysis/src/org/polarsys/capella/core/sirius/analysis/extension/style/FunctionalExchangeStyleConfiguration.java
  core/plugins/org.polarsys.capella.core.sirius.analysis/src/org/polarsys/capella/core/sirius/analysis/refresh/extension/ComponentArchitectureBlankRefreshExtension.java
  core/plugins/org.polarsys.capella.core.sirius.analysis/src/org/polarsys/capella/core/sirius/analysis/refresh/extension/DataFlowBlankRefreshExtension.java
  tests/plugins/org.polarsys.capella.test.diagram.common.ju/src/org/polarsys/capella/test/diagram/common/ju/context/XABDiagram.java
  tests/plugins/org.polarsys.capella.test.diagram.misc.ju/model/EOLE_AF_UC/EOLE_AF_UC.aird
  tests/plugins/org.polarsys.capella.test.diagram.tools.ju/src/org/polarsys/capella/test/diagram/tools/ju/testsuites/partial/XABDiagramToolsTestSuite.java
  tests/plugins/org.polarsys.capella.test.diagram.tools.ju/src/org/polarsys/capella/test/diagram/tools/ju/xab/PhysicalLinkIconAndLabel.java
  tests/plugins/org.polarsys.capella.test.odesign/src/org/polarsys/capella/test/odesign/identifier/ToolAndLabelCoherenceTest.java
Labels: build-unstable

#2077 [releng][oomph] Update setup
  releng/plugins/org.polarsys.capella.settings/oomph/Capella.setup
Labels: build-unstable

#2086 #2085 Update doc with State Machine Validation Rule
  doc/plugins/org.polarsys.capella.validation.doc/html/Validation Rules/design/well-formedness/state_machines/ValidationRules.html
  doc/plugins/org.polarsys.capella.validation.doc/html/Validation Rules/design/well-formedness/state_machines/ValidationRules.mediawiki
Labels: build-started

#2072 #2071 Deprecated polarsys links updated with Eclipse
  doc/plugins/org.polarsys.capella.core.ui.intro/intro/firststeps-doc.xml
  doc/plugins/org.polarsys.capella.developer.doc/html/Capella Studio.html
  doc/plugins/org.polarsys.capella.developer.doc/html/Capella Studio.mediawiki
  doc/plugins/org.polarsys.capella.developer.doc/html/Tutorials.html
  doc/plugins/org.polarsys.capella.developer.doc/html/Tutorials.mediawiki
  doc/plugins/org.polarsys.capella.doc/html/Release note/API_1.0.x_to_1.1.x.html
  doc/plugins/org.polarsys.capella.doc/html/Release note/API_1.0.x_to_1.1.x.mediawiki
  doc/plugins/org.polarsys.capella.doc/html/Release note/KnownIssues.html
  doc/plugins/org.polarsys.capella.doc/html/Release note/KnownIssues.mediawiki
Labels: build-unstable

#2083 #2082 Migration contribution to not to display icon and label for Physical Paths and Functional Chains
  core/plugins/org.polarsys.capella.core.data.migration/plugin.xml
  core/plugins/org.polarsys.capella.core.data.migration/src/org/polarsys/capella/core/data/migration/contribution/EnableFCAndPPFiltersMigrationContribution.java
  tests/plugins/org.polarsys.capella.test.migration.ju/model/activate-filters-1_4_x/.project
  tests/plugins/org.polarsys.capella.test.migration.ju/model/activate-filters-1_4_x/activate-filters-1_4_x.afm
  tests/plugins/org.polarsys.capella.test.migration.ju/model/activate-filters-1_4_x/activate-filters-1_4_x.aird
  tests/plugins/org.polarsys.capella.test.migration.ju/model/activate-filters-1_4_x/activate-filters-1_4_x.melodymodeller
  tests/plugins/org.polarsys.capella.test.migration.ju/model/activate-filters-5_0_0/.project
  tests/plugins/org.polarsys.capella.test.migration.ju/model/activate-filters-5_0_0/activate-filters-5_0_0.afm
  tests/plugins/org.polarsys.capella.test.migration.ju/model/activate-filters-5_0_0/activate-filters-5_0_0.aird
  tests/plugins/org.polarsys.capella.test.migration.ju/model/activate-filters-5_0_0/activate-filters-5_0_0.capella
  tests/plugins/org.polarsys.capella.test.migration.ju/model/activate-filters-5_1_0/.project
  tests/plugins/org.polarsys.capella.test.migration.ju/model/activate-filters-5_1_0/activate-filters-5_1_0.afm
  tests/plugins/org.polarsys.capella.test.migration.ju/model/activate-filters-5_1_0/activate-filters-5_1_0.aird
  tests/plugins/org.polarsys.capella.test.migration.ju/model/activate-filters-5_1_0/activate-filters-5_1_0.capella
  tests/plugins/org.polarsys.capella.test.migration.ju/src/org/polarsys/capella/test/migration/ju/testcases/basic/EnableFCAndPPFiltersMigrationTest.java
  tests/plugins/org.polarsys.capella.test.migration.ju/src/org/polarsys/capella/test/migration/ju/testsuites/main/MigrationTestSuite.java
Labels: build-aborted, build-unstable

#2081 #2065 Add the documentation for pie icon/label for overlapped physical paths/functional chains
  doc/plugins/org.polarsys.capella.ui.doc/html/05. Diagram Management/5.5. Creation of Functional Chains and Physical Paths.html
  doc/plugins/org.polarsys.capella.ui.doc/html/05. Diagram Management/5.5. Creation of Functional Chains and Physical Paths.mediawiki
  doc/plugins/org.polarsys.capella.ui.doc/html/05. Diagram Management/Images/OverlappedPPFilters.png
  doc/plugins/org.polarsys.capella.ui.doc/html/05. Diagram Management/Images/OverlappedPPLabels.png
  doc/plugins/org.polarsys.capella.ui.doc/html/05. Diagram Management/Images/OverlappedPPs.png
  doc/plugins/org.polarsys.capella.ui.doc/license.txt
  doc/plugins/org.polarsys.capella.ui.doc/toc.xml
Labels: build-unstable

#2079 #2080 Display black internal links instead of many ones
  core/plugins/org.polarsys.capella.core.sirius.analysis/description/context.odesign
  core/plugins/org.polarsys.capella.core.sirius.analysis/description/logical.odesign
  core/plugins/org.polarsys.capella.core.sirius.analysis/description/physical.odesign
  core/plugins/org.polarsys.capella.core.sirius.analysis/src/org/polarsys/capella/core/sirius/analysis/ABServices.java
  core/plugins/org.polarsys.capella.core.sirius.analysis/src/org/polarsys/capella/core/sirius/analysis/DiagramServices.java
  core/plugins/org.polarsys.capella.core.sirius.analysis/src/org/polarsys/capella/core/sirius/analysis/FunctionalChainServices.java
  core/plugins/org.polarsys.capella.core.sirius.analysis/src/org/polarsys/capella/core/sirius/analysis/PhysicalServices.java
  tests/plugins/org.polarsys.capella.test.diagram.tools.ju/model/BlackInternalLinks/.project
  tests/plugins/org.polarsys.capella.test.diagram.tools.ju/model/BlackInternalLinks/BlackInternalLinks.afm
  tests/plugins/org.polarsys.capella.test.diagram.tools.ju/model/BlackInternalLinks/BlackInternalLinks.aird
  tests/plugins/org.polarsys.capella.test.diagram.tools.ju/model/BlackInternalLinks/BlackInternalLinks.capella
  tests/plugins/org.polarsys.capella.test.diagram.tools.ju/src/org/polarsys/capella/test/diagram/tools/ju/common/BlackInternalLinks.java
  tests/plugins/org.polarsys.capella.test.diagram.tools.ju/src/org/polarsys/capella/test/diagram/tools/ju/testsuites/partial/CommonToolsTestSuite.java
Labels: build-unstable

#2089 #2088 Add filters for Functional Chains and Paths internal links
  core/plugins/org.polarsys.capella.core.sirius.analysis/description/context.odesign
  core/plugins/org.polarsys.capella.core.sirius.analysis/description/logical.odesign
  core/plugins/org.polarsys.capella.core.sirius.analysis/description/physical.odesign
  core/plugins/org.polarsys.capella.core.sirius.analysis/plugin.properties
  core/plugins/org.polarsys.capella.core.sirius.analysis/src/org/polarsys/capella/core/sirius/analysis/constants/IFilterNameConstants.java
  tests/plugins/org.polarsys.capella.test.diagram.filters.ju/model/InternalLinks/.project
  tests/plugins/org.polarsys.capella.test.diagram.filters.ju/model/InternalLinks/InternalLinks.afm
  tests/plugins/org.polarsys.capella.test.diagram.filters.ju/model/InternalLinks/InternalLinks.aird
  tests/plugins/org.polarsys.capella.test.diagram.filters.ju/model/InternalLinks/InternalLinks.capella
  tests/plugins/org.polarsys.capella.test.diagram.filters.ju/src/org/polarsys/capella/test/diagram/filters/ju/model/InternalLinks.java
  tests/plugins/org.polarsys.capella.test.diagram.filters.ju/src/org/polarsys/capella/test/diagram/filters/ju/testsuites/DiagramFiltersTestSuite.java
  tests/plugins/org.polarsys.capella.test.diagram.filters.ju/src/org/polarsys/capella/test/diagram/filters/ju/xab/HideFCInternalLinksLAB.java
  tests/plugins/org.polarsys.capella.test.diagram.filters.ju/src/org/polarsys/capella/test/diagram/filters/ju/xab/HideFCInternalLinksLDFB.java
  tests/plugins/org.polarsys.capella.test.diagram.filters.ju/src/org/polarsys/capella/test/diagram/filters/ju/xab/HideFCInternalLinksPAB.java
  tests/plugins/org.polarsys.capella.test.diagram.filters.ju/src/org/polarsys/capella/test/diagram/filters/ju/xab/HideFCInternalLinksPDFB.java
  tests/plugins/org.polarsys.capella.test.diagram.filters.ju/src/org/polarsys/capella/test/diagram/filters/ju/xab/HideFCInternalLinksSAB.java
  tests/plugins/org.polarsys.capella.test.diagram.filters.ju/src/org/polarsys/capella/test/diagram/filters/ju/xab/HideFCInternalLinksSDFB.java
  tests/plugins/org.polarsys.capella.test.diagram.filters.ju/src/org/polarsys/capella/test/diagram/filters/ju/xab/HidePPInternalLinksLAB.java
  tests/plugins/org.polarsys.capella.test.diagram.filters.ju/src/org/polarsys/capella/test/diagram/filters/ju/xab/HidePPInternalLinksPAB.java
  tests/plugins/org.polarsys.capella.test.diagram.filters.ju/src/org/polarsys/capella/test/diagram/filters/ju/xab/HidePPInternalLinksSAB.java
  tests/plugins/org.polarsys.capella.test.diagram.filters.ju/src/org/polarsys/capella/test/diagram/filters/ju/xab/XABDiagramFiltersTestSuite.java
  tests/plugins/org.polarsys.capella.test.odesign/src/org/polarsys/capella/test/odesign/identifier/ToolAndLabelCoherenceTest.java
Labels: build-unstable, review-requested :lollipop:

#2091 #2075 Fix failing junit
  tests/plugins/org.polarsys.capella.test.framework/src/org/polarsys/capella/test/framework/helpers/SkeletonHelper.java
Labels: build-unstable, review-requested :lollipop:

#2093 #2092 Improve physical path graph display
  core/plugins/org.polarsys.capella.core.model.helpers/META-INF/MANIFEST.MF
  core/plugins/org.polarsys.capella.core.model.helpers/src/org/polarsys/capella/core/model/helpers/graph/GraphEdge.java
  core/plugins/org.polarsys.capella.core.model.helpers/src/org/polarsys/capella/core/model/helpers/graph/GraphNode.java
  core/plugins/org.polarsys.capella.core.model.helpers/src/org/polarsys/capella/core/model/helpers/graph/PhysicalPathInternalLink.java
  core/plugins/org.polarsys.capella.core.model.helpers/src/org/polarsys/capella/core/model/helpers/graph/PhysicalPathInternalLinksGraph.java
  core/plugins/org.polarsys.capella.core.model.helpers/src/org/polarsys/capella/core/model/helpers/graph/PhysicalPathInvolvementGraph.java
  core/plugins/org.polarsys.capella.core.model.helpers/src/org/polarsys/capella/core/model/helpers/graph/PhysicalPathInvolvementLink.java
  core/plugins/org.polarsys.capella.core.sirius.analysis/src/org/polarsys/capella/core/sirius/analysis/DiagramServices.java
  core/plugins/org.polarsys.capella.core.sirius.analysis/src/org/polarsys/capella/core/sirius/analysis/PhysicalServices.java
  core/plugins/org.polarsys.capella.core.sirius.analysis/src/org/polarsys/capella/core/sirius/analysis/cache/PhysicalPathCache.java
  core/plugins/org.polarsys.capella.core.sirius.analysis/src/org/polarsys/capella/core/sirius/analysis/refresh/extension/ComponentArchitectureBlankRefreshExtension.java
  core/plugins/org.polarsys.capella.core.sirius.analysis/src/org/polarsys/capella/core/sirius/analysis/refresh/extension/ContextualCapabilityRealizationInvolvementRefreshExtension.java
  tests/plugins/org.polarsys.capella.test.diagram.misc.ju/src/org/polarsys/capella/test/diagram/misc/ju/testcases/Bug1917TestCase.java
  tests/plugins/org.polarsys.capella.test.diagram.tools.ju/model/PhysicalPathDisplay/.project
  tests/plugins/org.polarsys.capella.test.diagram.tools.ju/model/PhysicalPathDisplay/PhysicalPathDisplay.afm
  tests/plugins/org.polarsys.capella.test.diagram.tools.ju/model/PhysicalPathDisplay/PhysicalPathDisplay.aird
  tests/plugins/org.polarsys.capella.test.diagram.tools.ju/model/PhysicalPathDisplay/PhysicalPathDisplay.capella
  tests/plugins/org.polarsys.capella.test.diagram.tools.ju/src/org/polarsys/capella/test/diagram/tools/ju/testsuites/partial/XABDiagramToolsTestSuite.java
  tests/plugins/org.polarsys.capella.test.diagram.tools.ju/src/org/polarsys/capella/test/diagram/tools/ju/xab/PhysicalPathDisplay.java
Labels: build-unstable, review-requested :lollipop:

#2096 #2065 Activate by default the filter "Hide label for overlapped Physical Paths" in PAB diagrams
  core/plugins/org.polarsys.capella.core.sirius.analysis/description/physical.odesign
Labels: build-unstable

#2097 #2071 Deprecated Polarsys
  doc/plugins/org.polarsys.capella.core.ui.intro/intro/firststeps-doc.xml
Labels: build-unstable

#2087 #2024 Constraint changes
  core/plugins/org.polarsys.capella.core.data.core.ui.quickfix/plugin.properties
  core/plugins/org.polarsys.capella.core.data.core.ui.quickfix/plugin.xml
  core/plugins/org.polarsys.capella.core.data.core.ui.quickfix/src/org/polarsys/capella/core/data/core/ui/quickfix/resolver/ConstraintAssignmentRule_Resolver.java
  core/plugins/org.polarsys.capella.core.data.core.ui.quickfix/src/org/polarsys/capella/core/data/core/ui/quickfix/resolver/ConstraintLocationRule_Resolver.java
  core/plugins/org.polarsys.capella.core.data.core.validation/META-INF/MANIFEST.MF
  core/plugins/org.polarsys.capella.core.data.core.validation/plugin.xml
  core/plugins/org.polarsys.capella.core.data.core.validation/src/org/polarsys/capella/core/data/capellamodeller/validation/ConstraintAssignmentRule.java
  core/plugins/org.polarsys.capella.core.data.core.validation/src/org/polarsys/capella/core/data/capellamodeller/validation/ConstraintLocationRule.java
  core/plugins/org.polarsys.capella.core.semantic.queries/src/org/polarsys/capella/core/semantic/queries/basic/queries/ModelElementConstraints.java
  core/plugins/org.polarsys.capella.core.sirius.analysis/description/physical.odesign
  core/plugins/org.polarsys.capella.core.sirius.analysis/src/org/polarsys/capella/core/sirius/analysis/CsServices.java
Labels: build-unstable

#2102 #2101 Extend Interpreter View popup menu
  core/plugins/org.polarsys.capella.core.platform.sirius.ui.menu/plugin.xml
  core/plugins/org.polarsys.capella.core.sirius.ui/icons/copy.gif
  core/plugins/org.polarsys.capella.core.sirius.ui/icons/license.txt
  core/plugins/org.polarsys.capella.core.sirius.ui/plugin.properties
  core/plugins/org.polarsys.capella.core.sirius.ui/plugin.xml
  core/plugins/org.polarsys.capella.core.sirius.ui/src/org/polarsys/capella/core/sirius/ui/handlers/AbstractDiagramCommandHandler.java
  core/plugins/org.polarsys.capella.core.sirius.ui/src/org/polarsys/capella/core/sirius/ui/handlers/CopyTextHandler.java
Labels: build-unstable
