Repository eclipse-capella/capella, pull requests merged in 2021-04, with the labels that each got.

#2156 #2106 Use ScenarioCache in Operand and Fragment computation
  core/plugins/org.polarsys.capella.core.sirius.analysis/src/org/polarsys/capella/core/sequencediag/ScenarioService.java
  core/plugins/org.polarsys.capella.core.sirius.analysis/src/org/polarsys/capella/core/sirius/analysis/SequenceDiagramServices.java
  core/plugins/org.polarsys.capella.core.sirius.analysis/src/org/polarsys/capella/core/sirius/analysis/cache/ScenarioCache.java
Labels: build-successfull

#2158 #2033 Remove XHTML add-on Command Line documentation section
  doc/plugins/org.polarsys.capella.commandline.doc/.settings/org.eclipse.core.resources.prefs
  doc/plugins/org.polarsys.capella.commandline.doc/html/19. Command Line Support/19.1. Core Mechanism and Applications-toc.xml
  doc/plugins/org.polarsys.capella.commandline.doc/html/19. Command Line Support/19.1. Core Mechanism and Applications.html
  doc/plugins/org.polarsys.capella.commandline.doc/html/19. Command Line Support/19.1. Core Mechanism and Applications.mediawiki
  doc/plugins/org.polarsys.capella.commandline.doc/toc.xml
Labels: build-successfull

#2159 #2138 Handle when a fragment of a library is in conflict state
  core/plugins/org.polarsys.capella.core.model.handler/src/org/polarsys/capella/core/model/handler/command/CapellaResourceHelper.java
  core/plugins/org.polarsys.capella.core.platform.sirius.ui.actions/src/org/polarsys/capella/core/platform/sirius/ui/session/GitConflictHelper.java
  tests/plugins/org.polarsys.capella.test.model.ju/model/gch-library/.project
  tests/plugins/org.polarsys.capella.test.model.ju/model/gch-library/fragments/SA.airdfragment
  tests/plugins/org.polarsys.capella.test.model.ju/model/gch-library/fragments/SA.capellafragment
  tests/plugins/org.polarsys.capella.test.model.ju/model/gch-library/gch-library.afm
  tests/plugins/org.polarsys.capella.test.model.ju/model/gch-library/gch-library.aird
  tests/plugins/org.polarsys.capella.test.model.ju/model/gch-library/gch-library.capella
  tests/plugins/org.polarsys.capella.test.model.ju/model/gch-project/.project
  tests/plugins/org.polarsys.capella.test.model.ju/model/gch-project/fragments/SA.airdfragment
  tests/plugins/org.polarsys.capella.test.model.ju/model/gch-project/fragments/SA.capellafragment
  tests/plugins/org.polarsys.capella.test.model.ju/model/gch-project/gch-project.afm
  tests/plugins/org.polarsys.capella.test.model.ju/model/gch-project/gch-project.aird
  tests/plugins/org.polarsys.capella.test.model.ju/model/gch-project/gch-project.capella
  tests/plugins/org.polarsys.capella.test.model.ju/src/org/polarsys/capella/test/model/ju/helpers/GitConflictHelperTest.java
  tests/plugins/org.polarsys.capella.test.model.ju/src/org/polarsys/capella/test/model/ju/testsuites/main/ModelTestSuite.java
Labels: build-aborted, build-successfull

#2161 #2160 Remove Diagram tab from aird properties page
  core/plugins/org.polarsys.capella.core.sirius.analysis/plugin.xml
Labels: build-successfull

#2162 #2163 Export Representation queries from org.polarsys.capella.core.semantic.queries
  core/plugins/org.polarsys.capella.core.semantic.queries/META-INF/MANIFEST.MF
Labels: build-successfull, to: squash :cookie:

#2157 #2151 Disable menus on empty selection
  core/plugins/org.polarsys.capella.core.data.migration/plugin.xml
  core/plugins/org.polarsys.capella.core.data.migration/src/org/polarsys/capella/core/data/migration/handlers/MigrationPropertyTester.java
  core/plugins/org.polarsys.capella.core.ui.semantic.browser.sirius/plugin.xml
  core/plugins/org.polarsys.capella.core.validation.ui/src/org/polarsys/capella/core/validation/ui/DynamicActionProvider.java
Labels: build-successfull, to: squash :cookie:

#2166 [2165] Default Log Configuration deep copy
  common/plugins/org.polarsys.capella.common.tools.report/src/org/polarsys/capella/common/tools/report/config/persistence/OutputConfiguration.java
  tests/plugins/org.polarsys.capella.test.platform.ju/src/org/polarsys/capella/test/platform/ju/testcases/CapellaLoggerConfigTestCase.java
  tests/plugins/org.polarsys.capella.test.platform.ju/src/org/polarsys/capella/test/platform/ju/testcases/JobLogTest.java
  tests/plugins/org.polarsys.capella.test.platform.ju/src/org/polarsys/capella/test/platform/ju/testsuites/PlatformTestSuite.java
Labels: build-successfull

#2169 [releng] Update Sirius version to 6.5.0-S20210419-114904
  releng/plugins/org.polarsys.capella.settings/oomph/Capella.setup
  releng/plugins/org.polarsys.capella.targets/full/capella.target-definition.targetplatform
Labels: build-successfull

#2172 #2171 Migration aird delegated handlers are wrongly called on non aird resources
  core/plugins/org.polarsys.capella.core.data.migration/src/org/polarsys/capella/core/data/migration/aird/AirdMigrationRunnable.java
  core/plugins/org.polarsys.capella.core.data.migration/src/org/polarsys/capella/core/data/migration/aird/SiriusMigrationContribution.java
  tests/plugins/org.polarsys.capella.test.migration.ju/src/org/polarsys/capella/test/migration/ju/testcases/basic/MigrationDelegatedHandlerTest.java
  tests/plugins/org.polarsys.capella.test.migration.ju/src/org/polarsys/capella/test/migration/ju/testsuites/main/MigrationTestSuite.java
Labels: build-successfull

#2175 #2174 Resources column empty on validate from cmd line
  common/plugins/org.polarsys.capella.common.tools.report.appenders.reportlogview/src/org/polarsys/capella/common/tools/report/appenders/reportlogview/LightMarkerRegistry.java
  tests/plugins/org.polarsys.capella.test.commandline.ju/src/org/polarsys/capella/test/commandline/ju/testcases/CommandLineValidationTest.java
Labels: build-successfull

#2176 [doc] Add dependency versions reference
  doc/plugins/org.polarsys.capella.doc/html/Release note/DependencyVersions.html
  doc/plugins/org.polarsys.capella.doc/html/Release note/DependencyVersions.mediawiki
  doc/plugins/org.polarsys.capella.doc/toc.xml
Labels: build-successfull

#2177 [releng] Update Diffmerge 0.13.1-M2 and Kitalpha IT2
  releng/plugins/org.polarsys.capella.targets/full/capella.target-definition.targetplatform
Labels: build-successfull

#2179 #2178 XAB diagrams created from graphical model elements in mono-part
  core/plugins/org.polarsys.capella.core.model.handler/src/org/polarsys/capella/core/model/handler/helpers/CapellaProjectHelper.java
  core/plugins/org.polarsys.capella.core.model.handler/src/org/polarsys/capella/core/model/handler/helpers/RepresentationHelper.java
  core/plugins/org.polarsys.capella.core.sirius.analysis/src/org/polarsys/capella/core/sirius/analysis/CapellaServices.java
  core/plugins/org.polarsys.capella.core.sirius.analysis/src/org/polarsys/capella/core/sirius/analysis/refresh/extension/ComponentArchitectureBlankRefreshExtension.java
  tests/plugins/org.polarsys.capella.test.diagram.misc.ju/META-INF/MANIFEST.MF
  tests/plugins/org.polarsys.capella.test.diagram.misc.ju/model/diagrams-having-parts-as-targets/.project
  tests/plugins/org.polarsys.capella.test.diagram.misc.ju/model/diagrams-having-parts-as-targets/diagrams-having-parts-as-targets.afm
  tests/plugins/org.polarsys.capella.test.diagram.misc.ju/model/diagrams-having-parts-as-targets/diagrams-having-parts-as-targets.aird
  tests/plugins/org.polarsys.capella.test.diagram.misc.ju/model/diagrams-having-parts-as-targets/diagrams-having-parts-as-targets.capella
  tests/plugins/org.polarsys.capella.test.diagram.misc.ju/model/diagrams-having-parts-as-targets/diagrams-having-parts-as-targets.melodyconnector
  tests/plugins/org.polarsys.capella.test.diagram.misc.ju/src/org/polarsys/capella/test/diagram/misc/ju/testcases/DiagramTargetUpdateDuringRefreshTest.java
  tests/plugins/org.polarsys.capella.test.diagram.misc.ju/src/org/polarsys/capella/test/diagram/misc/ju/testsuites/DiagramMiscTestSuite.java
  tests/plugins/org.polarsys.capella.test.framework/src/org/polarsys/capella/test/framework/helpers/TestHelper.java
Labels: build-successfull

#2184 #2181 Test LCDecomposition
  tests/plugins/org.polarsys.capella.test.model.ju/model/lcdecomposition/lcdecomposition.aird
  tests/plugins/org.polarsys.capella.test.model.ju/model/lcdecomposition/lcdecomposition.capella
  tests/plugins/org.polarsys.capella.test.model.ju/src/org/polarsys/capella/test/model/ju/testcase/LCDecomposition/LCDecompositionAttachDetachCommunicationLinkInterface.java
  tests/plugins/org.polarsys.capella.test.model.ju/src/org/polarsys/capella/test/model/ju/testsuites/main/ModelTestSuite.java
Labels: build-successfull

#2186 #2185 Describe procedure to How to Unreference a Library
  doc/plugins/org.polarsys.capella.re.doc/build.xml
  doc/plugins/org.polarsys.capella.re.doc/html/08. Replicable Element (REC-RPL)/8.1. Introduction.html
  doc/plugins/org.polarsys.capella.re.doc/html/08. Replicable Element (REC-RPL)/8.2. Basic Use Case.html
  doc/plugins/org.polarsys.capella.re.doc/html/08. Replicable Element (REC-RPL)/8.3. Update REC-RPL.html
  doc/plugins/org.polarsys.capella.re.doc/html/08. Replicable Element (REC-RPL)/8.4. RPL Deletion.html
  doc/plugins/org.polarsys.capella.re.doc/html/08. Replicable Element (REC-RPL)/8.5. RPL Validation.html
  doc/plugins/org.polarsys.capella.re.doc/html/08. Replicable Element (REC-RPL)/8.6. Advanced Features.html
  doc/plugins/org.polarsys.capella.re.doc/html/09. Libraries/9.1. Introduction.html
  doc/plugins/org.polarsys.capella.re.doc/html/09. Libraries/9.1. Introduction.mediawiki
  doc/plugins/org.polarsys.capella.re.doc/html/09. Libraries/9.2. Basic Use Case.html
  doc/plugins/org.polarsys.capella.re.doc/html/09. Libraries/9.2. Basic Use Case.mediawiki
  doc/plugins/org.polarsys.capella.re.doc/html/09. Libraries/9.3. Usage With Replicable Elements.html
  doc/plugins/org.polarsys.capella.re.doc/html/09. Libraries/9.3. Usage With Replicable Elements.mediawiki
  doc/plugins/org.polarsys.capella.re.doc/html/09. Libraries/9.4. Usage Restrictions.html
  doc/plugins/org.polarsys.capella.re.doc/html/09. Libraries/9.4. Usage Restrictions.mediawiki
  doc/plugins/org.polarsys.capella.re.doc/html/09. Libraries/9.5. Advanced Operations.html
  doc/plugins/org.polarsys.capella.re.doc/html/09. Libraries/9.5. Advanced Operations.mediawiki
  doc/plugins/org.polarsys.capella.re.doc/html/09. Libraries/Images/Unreference-1.png
  doc/plugins/org.polarsys.capella.re.doc/html/09. Libraries/Images/Unreference-2.png
  doc/plugins/org.polarsys.capella.re.doc/html/09. Libraries/Images/Unreference-3.png
  doc/plugins/org.polarsys.capella.re.doc/html/09. Libraries/Images/Unreference-4.png
  doc/plugins/org.polarsys.capella.re.doc/html/09. Libraries/Images/Unreference-5.png
  doc/plugins/org.polarsys.capella.re.doc/license.txt
  doc/plugins/org.polarsys.capella.re.doc/toc.xml
Labels: build-successfull

#2183 [test] Add some migration framework junit
  core/plugins/org.polarsys.capella.core.platform.sirius.ui.actions/src/org/polarsys/capella/core/platform/sirius/ui/session/CapellaSessionHelper.java
  core/plugins/org.polarsys.capella.core.platform.sirius.ui.actions/src/org/polarsys/capella/core/platform/sirius/ui/session/Messages.java
  core/plugins/org.polarsys.capella.core.platform.sirius.ui.actions/src/org/polarsys/capella/core/platform/sirius/ui/session/messages.properties
  tests/plugins/org.polarsys.capella.test.migration.ju/META-INF/MANIFEST.MF
  tests/plugins/org.polarsys.capella.test.migration.ju/model/Migration.ecore
  tests/plugins/org.polarsys.capella.test.migration.ju/src/org/polarsys/capella/test/migration/ju/fwk/EFactoryTest.java
  tests/plugins/org.polarsys.capella.test.migration.ju/src/org/polarsys/capella/test/migration/ju/fwk/MigrationContributionTest.java
  tests/plugins/org.polarsys.capella.test.migration.ju/src/org/polarsys/capella/test/migration/ju/fwk/NsPrefixTest.java
  tests/plugins/org.polarsys.capella.test.migration.ju/src/org/polarsys/capella/test/migration/ju/fwk/PackageRegistryTest.java
  tests/plugins/org.polarsys.capella.test.migration.ju/src/org/polarsys/capella/test/migration/ju/fwk/TestOfTest.java
  tests/plugins/org.polarsys.capella.test.migration.ju/src/org/polarsys/capella/test/migration/ju/testsuites/main/MigrationTestSuite.java
Labels: build-successfull
