Repository eclipse-capella/capella, pull requests merged in 2021-11, with the labels that each got.

#2260 #2259 Enable creation of ES/AS from AbstractCapabilities (OA level)
  core/plugins/org.polarsys.capella.core.sirius.analysis/src/org/polarsys/capella/core/sirius/analysis/CapellaServices.java
  core/plugins/org.polarsys.capella.core.sirius.analysis/src/org/polarsys/capella/core/sirius/analysis/SequenceDiagramServices.java
Labels: build-successfull

#2262 #2261 Handle selection of transformation handlers
  common/plugins/org.polarsys.capella.common.transition/src/org/polarsys/capella/core/transition/common/handlers/traceability/config/ExtendedTraceabilityConfiguration.java
Labels: build-successfull

#2264 #2263 Capability Transition to EPBS creates some inconsistent Involvements
  core/plugins/org.polarsys.capella.core.transition.system.topdown/plugin.xml
  core/plugins/org.polarsys.capella.core.transition.system.topdown/src/org/polarsys/capella/core/transition/system/topdown/commands/IntramodelTransitionCommand.java
  core/plugins/org.polarsys.capella.core.transition.system.topdown/src/org/polarsys/capella/core/transition/system/topdown/constants/Messages.java
  core/plugins/org.polarsys.capella.core.transition.system.topdown/src/org/polarsys/capella/core/transition/system/topdown/constants/messages.properties
  core/plugins/org.polarsys.capella.core.transition.system.topdown/src/org/polarsys/capella/core/transition/system/topdown/rules/pa/PhysicalComponentRule.java
  core/plugins/org.polarsys.capella.core.transition.system/src/org/polarsys/capella/core/transition/system/rules/cs/ComponentRule.java
  tests/plugins/org.polarsys.capella.test.transition.ju/model/CreateRule_Scenario/CreateRule_Scenario.aird
  tests/plugins/org.polarsys.capella.test.transition.ju/model/CreateRule_Scenario/CreateRule_Scenario.capella
  tests/plugins/org.polarsys.capella.test.transition.ju/src/org/polarsys/capella/test/transition/ju/model/CreateRule_Scenario_IS2IS_EPBS.java
  tests/plugins/org.polarsys.capella.test.transition.ju/src/org/polarsys/capella/test/transition/ju/testsuites/main/TransitionsTestSuite.java
  tests/plugins/org.polarsys.capella.test.transition.ju/src/org/polarsys/capella/test/transition/ju/transitions/CreateRule_IS2IS_EPBS_04.java
Labels: build-successfull

#2268 #2267 Fixed DnD a property from a Association to another
  core/plugins/org.polarsys.capella.core.model.helpers/src/org/polarsys/capella/core/model/helpers/move/MoveHelper.java
  tests/plugins/org.polarsys.capella.test.navigator.ju/src/org/polarsys/capella/test/navigator/ju/DragDropTest.java
Labels: build-successfull

#2266 #2265 FC New menu contibution updated checks for OA level
  core/plugins/org.polarsys.capella.core.data.menu.contributions/META-INF/MANIFEST.MF
  core/plugins/org.polarsys.capella.core.data.menu.contributions/src/org/polarsys/capella/core/data/menu/contributions/fa/FunctionalChainItemContribution.java
Labels: build-started

#2271 #2270 Add missing Delete tools on Tables
  core/plugins/org.polarsys.capella.core.sirius.analysis/description/common.odesign
  core/plugins/org.polarsys.capella.core.sirius.analysis/description/context.odesign
  core/plugins/org.polarsys.capella.core.sirius.analysis/description/logical.odesign
  tests/plugins/org.polarsys.capella.test.diagram.common.ju/src/org/polarsys/capella/test/diagram/common/ju/wrapper/utils/ODesignHelper.java
  tests/plugins/org.polarsys.capella.test.odesign/src/org/polarsys/capella/test/odesign/ju/deletecheck/CheckDeletionDescriptionTest.java
  tests/plugins/org.polarsys.capella.test.table/src/org/polarsys/capella/test/table/ju/interfaces/InterfaceCapabilityScenarioTestCase.java
  tests/plugins/org.polarsys.capella.test.table/src/org/polarsys/capella/test/table/ju/interfaces/InterfaceCapabilityTestCase.java
  tests/plugins/org.polarsys.capella.test.table/src/org/polarsys/capella/test/table/ju/interfaces/InterfaceScenarioTestCase.java
  tests/plugins/org.polarsys.capella.test.table/src/org/polarsys/capella/test/table/ju/interfaces/InterfaceTableTestFramework.java
  tests/plugins/org.polarsys.capella.test.table/src/org/polarsys/capella/test/table/ju/requirements/RequirementsTableTestCase.java
  tests/plugins/org.polarsys.capella.test.table/src/org/polarsys/capella/test/table/ju/requirements/RequirementsTableTestFramework.java
Labels: build-unstable, build-aborted

#2272 #2263 Fix Random Test
  tests/plugins/org.polarsys.capella.test.transition.ju/model/CreateRule_Scenario/CreateRule_Scenario.aird
  tests/plugins/org.polarsys.capella.test.transition.ju/model/CreateRule_Scenario/CreateRule_Scenario.capella
  tests/plugins/org.polarsys.capella.test.transition.ju/src/org/polarsys/capella/test/transition/ju/model/CreateRule_Scenario_IS2IS_EPBS.java
Labels: build-successfull

#2285 [releng] Update Target platform for 5.2.0-IT3
  releng/plugins/org.polarsys.capella.targets/full/capella.target-definition.targetplatform
Labels: build-successfull
