Repository eclipse-capella/capella, pull requests merged in 2022-08, with the labels that each got.

#2438 [releng] Update Diffmerge
  common/plugins/org.polarsys.capella.common.transition/src/org/polarsys/capella/core/transition/common/merge/scope/TransitionSiriusImageHelper.java
  releng/plugins/org.polarsys.capella.targets/full/capella.target-definition.targetplatform
Labels: build-successfull

#2441 [Doc] Update documentation about the embed of JDK instead of JRE in
  doc/plugins/org.polarsys.capella.ui.doc/html/Installation Guide/How to install Capella and Addons.html
  doc/plugins/org.polarsys.capella.ui.doc/html/Installation Guide/How to install Capella and Addons.mediawiki
Labels: build-successfull

#2446 [Test] Update RCPTT tests to be compatible with Capella 6.0
  tests/plugins/org.polarsys.capella.test.rcptt/ActivityExplorer/MoveRepresentationInActivityExplorer.test
  tests/plugins/org.polarsys.capella.test.rcptt/Menu/MoveRepresentation.test
  tests/plugins/org.polarsys.capella.test.rcptt/ProjectExplorer/RenameCapellaProject.test
  tests/plugins/org.polarsys.capella.test.rcptt/SemanticBrowser/SemanticBrowserSelection.test
  tests/plugins/org.polarsys.capella.test.rcptt/models/renameTest/images/testMe.jpeg
  tests/plugins/org.polarsys.capella.test.rcptt/models/renameTest/renameTest.aird
Labels: build-unstable

#2447 #2442-update_toc.xml
  doc/plugins/org.polarsys.capella.doc/html/Release note/API_5.x_to_6.x.html
  doc/plugins/org.polarsys.capella.doc/html/Release note/API_5.x_to_6.x.mediawiki
  doc/plugins/org.polarsys.capella.doc/toc.xml
Labels: build-successfull

#2448 [doc] Update doc to reference Capella-Studio tutorials
  doc/plugins/org.polarsys.capella.developer.doc/html/Capella Studio.html
  doc/plugins/org.polarsys.capella.developer.doc/html/Capella Studio.mediawiki
  doc/plugins/org.polarsys.capella.developer.doc/html/Tutorials.html
  doc/plugins/org.polarsys.capella.developer.doc/html/Tutorials.mediawiki
  doc/plugins/org.polarsys.capella.developer.doc/html/Viewpoint Guidelines.html
  doc/plugins/org.polarsys.capella.developer.doc/html/Viewpoint Guidelines.mediawiki
  doc/plugins/org.polarsys.capella.developer.doc/toc.xml
Labels: build-unstable, to: merge-later 🔒

#2457 [doc] Regenerate developer.doc with build.xml
  doc/plugins/org.polarsys.capella.developer.doc/html/Capella Studio.html
  doc/plugins/org.polarsys.capella.developer.doc/html/Tutorials.html
Labels: build-successfull

#2454 [releng] Update Sirius 7.0.4 and Kitalpha
  releng/plugins/org.polarsys.capella.targets/full/capella.target-definition.targetplatform
Labels: build-unstable
