Repository eclipse-capella/capella, pull requests merged in 2022-09, with the labels that each got.

#2466 #2465: Fix migration issue with collapsed ports
  core/plugins/org.polarsys.capella.core.data.migration/META-INF/MANIFEST.MF
  core/plugins/org.polarsys.capella.core.data.migration/src/org/polarsys/capella/core/data/migration/Activator.java
  core/plugins/org.polarsys.capella.core.data.migration/src/org/polarsys/capella/core/data/migration/participant/CapellaWorkspaceImageGMFBoundsMigrationParticipant.java
Labels: build-successfull

#2464 #2450 Added "Show In Property Dialog" menu action
  core/plugins/org.polarsys.capella.core.ui.properties/icons/property_page.gif
  core/plugins/org.polarsys.capella.core.ui.properties/plugin.xml
  core/plugins/org.polarsys.capella.core.ui.properties/src/org/polarsys/capella/core/ui/properties/property/ShowInPropertiesDialogHandler.java
  tests/plugins/org.polarsys.capella.test.navigator.ju/META-INF/MANIFEST.MF
  tests/plugins/org.polarsys.capella.test.navigator.ju/src/org/polarsys/capella/test/navigator/ju/ShowInPropertiesDialogTest.java
  tests/plugins/org.polarsys.capella.test.navigator.ju/src/org/polarsys/capella/test/navigator/ju/testsuites/main/NavigatorUITestSuite.java
Labels: build-successfull, to: merge-later 🔒

#2468 Revert "#2450 Added "Show In Property Dialog" menu action"
  core/plugins/org.polarsys.capella.core.ui.properties/icons/property_page.gif
  core/plugins/org.polarsys.capella.core.ui.properties/plugin.xml
  core/plugins/org.polarsys.capella.core.ui.properties/src/org/polarsys/capella/core/ui/properties/property/ShowInPropertiesDialogHandler.java
  tests/plugins/org.polarsys.capella.test.navigator.ju/META-INF/MANIFEST.MF
  tests/plugins/org.polarsys.capella.test.navigator.ju/src/org/polarsys/capella/test/navigator/ju/ShowInPropertiesDialogTest.java
  tests/plugins/org.polarsys.capella.test.navigator.ju/src/org/polarsys/capella/test/navigator/ju/testsuites/main/NavigatorUITestSuite.java
Labels: build-started

#2439 #1939 branch add exchange categories filter
  core/plugins/org.polarsys.capella.core.platform.sirius.ui.navigator/plugin.xml
Labels: build-successfull, to: merge-later 🔒

#2472 #2450 Added "Show In Property Dialog" menu action
  core/plugins/org.polarsys.capella.core.ui.properties/icons/property_page.gif
  core/plugins/org.polarsys.capella.core.ui.properties/plugin.xml
  core/plugins/org.polarsys.capella.core.ui.properties/src/org/polarsys/capella/core/ui/properties/property/ShowInPropertiesDialogHandler.java
  doc/plugins/org.polarsys.capella.ui.doc/html/04. User Interface/4.06. Properties View.html
  doc/plugins/org.polarsys.capella.ui.doc/html/04. User Interface/4.06. Properties View.mediawiki
  doc/plugins/org.polarsys.capella.ui.doc/html/04. User Interface/Images/4.06_Properties_View_Contextual_Menu.png
  tests/plugins/org.polarsys.capella.test.navigator.ju/META-INF/MANIFEST.MF
  tests/plugins/org.polarsys.capella.test.navigator.ju/src/org/polarsys/capella/test/navigator/ju/ShowInPropertiesDialogTest.java
  tests/plugins/org.polarsys.capella.test.navigator.ju/src/org/polarsys/capella/test/navigator/ju/testsuites/main/NavigatorUITestSuite.java
Labels: build-successfull

#2474 Handle exception when clicking cancel on a subsystem transition
  common/plugins/org.polarsys.capella.common.transition/src/org/polarsys/capella/core/transition/common/activities/FinalizeTransitionActivity.java
Labels: build-successfull

#2477 #2453 Added semantic queries on External Referenced Elements
  core/plugins/org.polarsys.capella.core.data.helpers/src/org/polarsys/capella/core/data/helpers/ctx/services/CapabilityExt.java
  core/plugins/org.polarsys.capella.core.data.interaction.validation/src/org/polarsys/capella/core/data/interaction/validation/abstractCapability/MDCHK_Capability_FunctionalChains_Involvement.java
  core/plugins/org.polarsys.capella.core.semantic.queries/plugin.xml
  core/plugins/org.polarsys.capella.core.semantic.queries/src/org/polarsys/capella/core/semantic/queries/basic/queries/AbstractCapability_ExternalReferencedFunctionalChains.java
  core/plugins/org.polarsys.capella.core.semantic.queries/src/org/polarsys/capella/core/semantic/queries/basic/queries/AbstractCapability_ExternalReferencedScenarios.java
  core/plugins/org.polarsys.capella.core.semantic.queries/src/org/polarsys/capella/core/semantic/queries/basic/queries/FunctionalChain_ExternalReferencedFunctionalChains.java
  core/plugins/org.polarsys.capella.core.semantic.queries/src/org/polarsys/capella/core/semantic/queries/basic/queries/OperationalCapability_ExternalReferencedOperationalProcesses.java
  core/plugins/org.polarsys.capella.core.semantic.queries/src/org/polarsys/capella/core/semantic/queries/basic/queries/OperationalProcess_ExternalReferencedOperationalProcesses.java
  tests/plugins/org.polarsys.capella.test.semantic.queries.ju/model/SemanticQueries/SemanticQueries.aird
  tests/plugins/org.polarsys.capella.test.semantic.queries.ju/model/SemanticQueries/SemanticQueries.capella
  tests/plugins/org.polarsys.capella.test.semantic.queries.ju/src/org/polarsys/capella/test/semantic/queries/ju/AbstractSemanticQueryTestCase.java
  tests/plugins/org.polarsys.capella.test.semantic.queries.ju/src/org/polarsys/capella/test/semantic/queries/ju/model/SemanticQueries.java
  tests/plugins/org.polarsys.capella.test.semantic.queries.ju/src/org/polarsys/capella/test/semantic/queries/ju/testcases/Capability_ExternalReferencedFunctionalChains.java
  tests/plugins/org.polarsys.capella.test.semantic.queries.ju/src/org/polarsys/capella/test/semantic/queries/ju/testcases/Capability_ExternalReferencedScenarios.java
  tests/plugins/org.polarsys.capella.test.semantic.queries.ju/src/org/polarsys/capella/test/semantic/queries/ju/testcases/FunctionalChain_ExternalReferencedFunctionalChains.java
  tests/plugins/org.polarsys.capella.test.semantic.queries.ju/src/org/polarsys/capella/test/semantic/queries/ju/testcases/OperationalCapability_ExternalReferencedOperationalProcesses.java
  tests/plugins/org.polarsys.capella.test.semantic.queries.ju/src/org/polarsys/capella/test/semantic/queries/ju/testcases/OperationalProcess_ExternalReferencedOperationalProcesses.java
  tests/plugins/org.polarsys.capella.test.semantic.queries.ju/src/org/polarsys/capella/test/semantic/queries/ju/testsuites/SemanticQueriesTestSuite.java
  tests/plugins/org.polarsys.capella.test.validation.rules.ju/META-INF/MANIFEST.MF
  tests/plugins/org.polarsys.capella.test.validation.rules.ju/model/RulesOnDesignTest/RulesOnDesignTest.capella
  tests/plugins/org.polarsys.capella.test.validation.rules.ju/src/org/polarsys/capella/test/validation/rules/ju/testcases/dwf_ca/Rule_DWF_CA_09.java
Labels: build-successfull

#2479 #2478 Duplicate information in Delete dialog and Information view
  core/plugins/org.polarsys.capella.core.model.handler/src/org/polarsys/capella/core/model/handler/command/BasicCapellaDeleteCommand.java
  core/plugins/org.polarsys.capella.core.platform.sirius.ui.actions/src/org/polarsys/capella/core/platform/sirius/ui/commands/CapellaDeleteCommand.java
  core/plugins/org.polarsys.capella.core.platform.sirius.ui.actions/src/org/polarsys/capella/core/platform/sirius/ui/commands/Messages.java
  core/plugins/org.polarsys.capella.core.platform.sirius.ui.actions/src/org/polarsys/capella/core/platform/sirius/ui/commands/messages.properties
Labels: build-successfull

#2473 #2451 PP/OP/FC/Scenario Representation queries
  common/plugins/org.polarsys.capella.common.ui.toolkit.browser/src/org/polarsys/capella/common/ui/toolkit/browser/content/provider/impl/AbstractContentProvider.java
  core/plugins/org.polarsys.capella.core.ui.semantic.browser.sirius/META-INF/MANIFEST.MF
  core/plugins/org.polarsys.capella.core.ui.semantic.browser.sirius/plugin.xml
  core/plugins/org.polarsys.capella.core.ui.semantic.browser.sirius/src/org/polarsys/capella/core/ui/semantic/browser/sirius/content/provider/SiriusSemanticBrowserContentProviderFactory.java
  core/plugins/org.polarsys.capella.core.ui.semantic.browser.sirius/src/org/polarsys/capella/core/ui/semantic/browser/sirius/wrapper/CustomEObjectWrapper.java
  tests/plugins/org.polarsys.capella.test.semantic.ui.ju/META-INF/MANIFEST.MF
  tests/plugins/org.polarsys.capella.test.semantic.ui.ju/model/DiagramNavigationModel/DiagramNavigationModel.aird
  tests/plugins/org.polarsys.capella.test.semantic.ui.ju/src/org/polarsys/capella/test/semantic/ui/ju/testcases/SemanticBrowserRepresentationHasSemanticQueriesTest.java
  tests/plugins/org.polarsys.capella.test.semantic.ui.ju/src/org/polarsys/capella/test/semantic/ui/ju/testsuites/SemanticUITestSuite.java
Labels: build-successfull

#2484 #2483 Fixed missing icons in Diagram creation menu
  core/plugins/org.polarsys.capella.core.sirius.ui/src/org/polarsys/capella/core/sirius/ui/actions/AbstractNewRepresentationAction.java
  core/plugins/org.polarsys.capella.core.sirius.ui/src/org/polarsys/capella/core/sirius/ui/actions/OpenRepresentationsAction.java
  core/plugins/org.polarsys.capella.core.sirius.ui/src/org/polarsys/capella/core/sirius/ui/helper/DescriptionImageDescriptorHelper.java
Labels: build-successfull

#2488 #2449 Fixed double click on FC/PP/OP References
  core/plugins/org.polarsys.capella.core.platform.sirius.ui.navigator/src/org/polarsys/capella/core/platform/sirius/ui/navigator/actions/OpenRelatedDiagramAction.java
  core/plugins/org.polarsys.capella.core.preferences/src/org/polarsys/capella/core/commands/preferences/ui/sirius/DoubleClickBehaviourUtil.java
  core/plugins/org.polarsys.capella.core.sirius.analysis/src/org/polarsys/capella/core/sirius/analysis/policies/OpenRelatedDiagramEditPolicy.java
Labels: build-started

#2489 [#2487] Allocated ExchangeItems properly transitionned
  core/plugins/org.polarsys.capella.core.transition.system/src/org/polarsys/capella/core/transition/system/rules/fa/FunctionInputPortRule.java
  core/plugins/org.polarsys.capella.core.transition.system/src/org/polarsys/capella/core/transition/system/rules/fa/FunctionOutputPortRule.java
Labels: build-successfull

#2493 #2482 Fixed Capella Deletion wizard size
  common/plugins/org.polarsys.capella.common.ui/src/org/polarsys/capella/common/ui/toolkit/viewers/TreeAndListViewer.java
Labels: build-successfull

#2494 #2455 Changed filter in OAB from INT to I to be consistent with OAIB
  core/plugins/org.polarsys.capella.core.sirius.analysis/plugin.properties
Labels: build-successfull
