Repository eclipse-capella/capella, pull requests merged in 2023-03, with the labels that each got.

#2606 #2605 Fixed test that does not work in Team context
  tests/plugins/org.polarsys.capella.test.diagram.tools.ju/src/org/polarsys/capella/test/diagram/tools/ju/xab/PhysicalLinkIconAndLabel.java
Labels: build-successfull

#2610 #2609 Fixed JUnit on TitleBlock
  tests/plugins/org.polarsys.capella.test.odesign/src/org/polarsys/capella/test/odesign/ju/titleblock/CheckTitleBlockFilterTest.java
  tests/plugins/org.polarsys.capella.test.odesign/src/org/polarsys/capella/test/odesign/ju/titleblock/CheckTitleBlockMappingTest.java
  tests/plugins/org.polarsys.capella.test.odesign/src/org/polarsys/capella/test/odesign/ju/titleblock/CheckTitleBlockToolTest.java
Labels: build-successfull

#2612 [releng] Update to Sirius 7.1.0-S20230302-034329
  releng/plugins/org.polarsys.capella.targets/full/capella.target-definition.targetplatform
Labels: build-successfull

#2617 #2616 Added new quickfixes for I_23 Rule
  core/plugins/org.polarsys.capella.core.platform.sirius.sirius.validation/META-INF/MANIFEST.MF
  core/plugins/org.polarsys.capella.core.platform.sirius.sirius.validation/plugin.properties
  core/plugins/org.polarsys.capella.core.platform.sirius.sirius.validation/plugin.xml
  core/plugins/org.polarsys.capella.core.platform.sirius.sirius.validation/src/org/polarsys/capella/core/platform/sirius/sirius/validation/ddiagram/AbstractReplaceInvalidHyperLinkInDescription.java
  core/plugins/org.polarsys.capella.core.platform.sirius.sirius.validation/src/org/polarsys/capella/core/platform/sirius/sirius/validation/ddiagram/I_23_AbstractReplaceElementResolver.java
  core/plugins/org.polarsys.capella.core.platform.sirius.sirius.validation/src/org/polarsys/capella/core/platform/sirius/sirius/validation/ddiagram/I_23_ReplaceWithCapellaElementResolver.java
  core/plugins/org.polarsys.capella.core.platform.sirius.sirius.validation/src/org/polarsys/capella/core/platform/sirius/sirius/validation/ddiagram/I_23_ReplaceWithDiagramElementResolver.java
  core/plugins/org.polarsys.capella.core.platform.sirius.sirius.validation/src/org/polarsys/capella/core/platform/sirius/sirius/validation/ddiagram/ReplaceInvalidHyperLinkInDescriptionWithCapellaElement.java
  core/plugins/org.polarsys.capella.core.platform.sirius.sirius.validation/src/org/polarsys/capella/core/platform/sirius/sirius/validation/ddiagram/ReplaceInvalidHyperLinkInDescriptionWithDiagramElement.java
  core/plugins/org.polarsys.capella.core.platform.sirius.sirius.validation/src/org/polarsys/capella/core/platform/sirius/sirius/validation/parser/helper/DescriptionLinkParserHandler.java
  core/plugins/org.polarsys.capella.core.platform.sirius.sirius.validation/src/org/polarsys/capella/core/platform/sirius/sirius/validation/parser/helper/DescriptionParserHelper.java
  core/plugins/org.polarsys.capella.core.platform.sirius.sirius.validation/src/org/polarsys/capella/core/platform/sirius/sirius/validation/parser/helper/MissingElementHandler.java
  releng/plugins/org.polarsys.capella.targets/full/capella.target-definition.targetplatform
  tests/plugins/org.polarsys.capella.test.validation.rules.ju/META-INF/MANIFEST.MF
  tests/plugins/org.polarsys.capella.test.validation.rules.ju/model/RulesOnIntegrityTest/RulesOnIntegrityTest.aird
  tests/plugins/org.polarsys.capella.test.validation.rules.ju/model/RulesOnIntegrityTest/RulesOnIntegrityTest.capella
  tests/plugins/org.polarsys.capella.test.validation.rules.ju/src/org/polarsys/capella/test/validation/rules/ju/testcases/i/Rule_I_23.java
Labels: to: squash :cookie:, build-successfull

#2595 [Test] Migrate RCPTT tests
  tests/plugins/org.polarsys.capella.test.rcptt/CopyPasteCut/CopyPasteWithZoom.test
  tests/plugins/org.polarsys.capella.test.rcptt/Library/AccessPolicyRecRpl.test
  tests/plugins/org.polarsys.capella.test.rcptt/MassActions/SendTo/MESendToFromProjectExplorer.test
  tests/plugins/org.polarsys.capella.test.rcptt/MassActions/SendTo/MVSendToFromProjectExplorer.test
  tests/plugins/org.polarsys.capella.test.rcptt/Menu/NavigationMenu.test
  tests/plugins/org.polarsys.capella.test.rcptt/ProjectExplorer/LocatedElementIsFilteredInCapellaExplorer_GoTo.test
  tests/plugins/org.polarsys.capella.test.rcptt/ProjectExplorer/QuickFiltersMenuTest.test
  tests/plugins/org.polarsys.capella.test.rcptt/RecRpl/RecRpl.test
  tests/plugins/org.polarsys.capella.test.rcptt/Sequence/FunctionalExchangeWhenAllocationWithoutTarget.test
  tests/plugins/org.polarsys.capella.test.rcptt/Sequence/PrePostConditionDeletionImpactAnalysis.test
  tests/plugins/org.polarsys.capella.test.rcptt/TraceElements/TraceManagerWizard.test
  tests/plugins/org.polarsys.capella.test.rcptt/ValidationProfile/ProjectConfiguration.test
  tests/plugins/org.polarsys.capella.test.rcptt/contexts/default/CapellaEnableHiddenCapabilities.ctx
  tests/plugins/org.polarsys.capella.test.rcptt/contexts/default/CapellaExplorerFilters.ctx
  tests/plugins/org.polarsys.capella.test.rcptt/rcptt.properties
Labels: build-successfull

#2620 [releng] Update Kitalpha and Diffmerge
  common/plugins/org.polarsys.capella.common.transition/src/org/polarsys/capella/core/transition/common/merge/ExtendedComparison.java
  releng/plugins/org.polarsys.capella.targets/full/capella.target-definition.targetplatform
Labels: build-successfull

#2627 #2594 Fixed qf I_22, I_23 for all elements
  core/plugins/org.polarsys.capella.core.platform.sirius.sirius.validation/META-INF/MANIFEST.MF
  core/plugins/org.polarsys.capella.core.platform.sirius.sirius.validation/src/org/polarsys/capella/core/platform/sirius/sirius/validation/ddiagram/I_22_Resolver.java
  core/plugins/org.polarsys.capella.core.platform.sirius.sirius.validation/src/org/polarsys/capella/core/platform/sirius/sirius/validation/parser/helper/DescriptionParserHelper.java
  core/plugins/org.polarsys.capella.core.platform.sirius.sirius.validation/src/org/polarsys/capella/core/platform/sirius/sirius/validation/parser/helper/InvalidNameHandler.java
  core/plugins/org.polarsys.capella.core.platform.sirius.sirius.validation/src/org/polarsys/capella/core/platform/sirius/sirius/validation/parser/helper/MissingElementHandler.java
Labels: build-successfull

#2626 #2624 Fixed Invalid hyperlink detection on referenced diagrams
  core/plugins/org.polarsys.capella.core.model.handler/src/org/polarsys/capella/core/model/handler/helpers/RepresentationHelper.java
  core/plugins/org.polarsys.capella.core.model.helpers/src/org/polarsys/capella/core/model/utils/saxparser/SaxParserHelper.java
  core/plugins/org.polarsys.capella.core.model.helpers/src/org/polarsys/capella/core/model/utils/saxparser/WriteCapellaElementDescriptionSAXParser.java
  core/plugins/org.polarsys.capella.core.platform.sirius.sirius.validation/src/org/polarsys/capella/core/platform/sirius/sirius/validation/parser/helper/InvalidNameHandler.java
  core/plugins/org.polarsys.capella.core.ui.properties.richtext/src/org/polarsys/capella/core/ui/properties/richtext/navigation/CapellaNavigationModelElement.java
Labels: build-successfull, build-aborted

#2631 Add aarch64 products
  Jenkinsfile
  pom.xml
  releng/plugins/org.polarsys.capella.rcp.product/pom.xml
Labels: build-successfull
