Repository eclipse-capella/capella, pull requests merged in 2023-02, with the labels that each got.

#2566 #2559 Fix Copy as Unique Identifier on diagram elements
  core/plugins/org.polarsys.capella.core.platform.sirius.ui.actions/src/org/polarsys/capella/core/platform/sirius/ui/handlers/CopyUniqueIdentifierHandler.java
Labels: build-successfull

#2565 #2554 Filter property sections via activity bindings
  common/plugins/org.polarsys.capella.common.flexibility.wizards/src/org/polarsys/capella/common/flexibility/wizards/ui/tabbed/FixedTabDescriptorProvider.java
Labels: build-successfull

#2571 #2570 Added Viewpoint Manager view in "Show view" menu
  core/plugins/org.polarsys.capella.core.platform.sirius.ui.perspective/plugin.xml
  doc/plugins/org.polarsys.capella.ui.doc/html/First steps with Capella/Images/3.1. Starting Melody Advance_html_15a02c99.png
  doc/plugins/org.polarsys.capella.viewpoint.doc/html/Images/ShowView_ViewpointManager.png
  doc/plugins/org.polarsys.capella.viewpoint.doc/html/Images/Windows_ShowView.png
  doc/plugins/org.polarsys.capella.viewpoint.doc/html/Images/Windows_ShowView_Other.png
  doc/plugins/org.polarsys.capella.viewpoint.doc/html/activation/activation.html
  doc/plugins/org.polarsys.capella.viewpoint.doc/html/activation/activation.mediawiki
Labels: build-started

#2574 #2573 FIX NPE error when canceling the "Export as" dialog (Filtering)
  common/plugins/org.polarsys.capella.common.ui/src/org/polarsys/capella/common/ui/toolkit/dialogs/AbstractExportDialog.java
Labels: build-aborted

#2568 #2567 Dummy fixes on Capella right click menus
  core/plugins/org.polarsys.capella.core.platform.sirius.ui.actions/plugin.properties
  core/plugins/org.polarsys.capella.core.platform.sirius.ui.actions/plugin.xml
  core/plugins/org.polarsys.capella.core.platform.sirius.ui.menu/plugin.xml
  core/plugins/org.polarsys.capella.core.platform.sirius.ui.perspective/plugin.xml
  core/plugins/org.polarsys.capella.core.sirius.analysis/description/context.odesign
  core/plugins/org.polarsys.capella.core.sirius.analysis/description/logical.odesign
  core/plugins/org.polarsys.capella.core.sirius.analysis/description/oa.odesign
  core/plugins/org.polarsys.capella.core.sirius.analysis/description/physical.odesign
  core/plugins/org.polarsys.capella.core.sirius.analysis/plugin.properties
  core/plugins/org.polarsys.capella.core.sirius.analysis/src/org/polarsys/capella/core/sirius/analysis/constants/MappingConstantsHelper.java
  core/plugins/org.polarsys.capella.core.sirius.ui/META-INF/MANIFEST.MF
  core/plugins/org.polarsys.capella.core.sirius.ui/plugin.xml
  core/plugins/org.polarsys.capella.core.sirius.ui/src/org/polarsys/capella/core/sirius/ui/handlers/CreateFunctionalChainActionHandler.java
  core/plugins/org.polarsys.capella.core.sirius.ui/src/org/polarsys/capella/core/sirius/ui/handlers/CreatePhysicalPathActionHandler.java
  core/plugins/org.polarsys.capella.core.sirius.ui/src/org/polarsys/capella/core/sirius/ui/testers/AbstractValidCategoryMenuTargetTester.java
  core/plugins/org.polarsys.capella.core.sirius.ui/src/org/polarsys/capella/core/sirius/ui/testers/ValidCECategoryMenuTargetTester.java
  core/plugins/org.polarsys.capella.core.sirius.ui/src/org/polarsys/capella/core/sirius/ui/testers/ValidFCMenuTargetTester.java
  core/plugins/org.polarsys.capella.core.sirius.ui/src/org/polarsys/capella/core/sirius/ui/testers/ValidFECategoryMenuTargetTester.java
  core/plugins/org.polarsys.capella.core.sirius.ui/src/org/polarsys/capella/core/sirius/ui/testers/ValidOPMenuTargetTester.java
  core/plugins/org.polarsys.capella.core.sirius.ui/src/org/polarsys/capella/core/sirius/ui/testers/ValidPLCategoryMenuTargetTester.java
  core/plugins/org.polarsys.capella.core.sirius.ui/src/org/polarsys/capella/core/sirius/ui/testers/ValidPPMenuTargetTester.java
  doc/plugins/org.polarsys.capella.ui.doc/html/07. Modelling Wizards and Accelerators/7.5. Categories Management.html
  doc/plugins/org.polarsys.capella.ui.doc/html/07. Modelling Wizards and Accelerators/7.5. Categories Management.mediawiki
  doc/plugins/org.polarsys.capella.ui.doc/html/07. Modelling Wizards and Accelerators/Images/7.5. Categories Management_html_63b85f83.png
  doc/plugins/org.polarsys.capella.ui.doc/html/07. Modelling Wizards and Accelerators/Images/7.5. Categories Management_html_m3bb20f50.png
  doc/plugins/org.polarsys.capella.ui.doc/html/07. Modelling Wizards and Accelerators/Images/7.5. Categories Management_html_m40dbbf55.png
  tests/plugins/org.polarsys.capella.test.diagram.common.ju/META-INF/MANIFEST.MF
  tests/plugins/org.polarsys.capella.test.diagram.common.ju/src/org/polarsys/capella/test/diagram/common/ju/context/CommonDiagram.java
  tests/plugins/org.polarsys.capella.test.diagram.common.ju/src/org/polarsys/capella/test/diagram/common/ju/context/XABDiagram.java
  tests/plugins/org.polarsys.capella.test.diagram.common.ju/src/org/polarsys/capella/test/diagram/common/ju/context/XDFBDiagram.java
  tests/plugins/org.polarsys.capella.test.odesign/src/org/polarsys/capella/test/odesign/identifier/allTools.txt
  tests/plugins/org.polarsys.capella.test.odesign/src/org/polarsys/capella/test/odesign/identifier/toolsToCheck.txt
Labels: build-started

#2579 #2578 Fixed blocker sonar issue
  core/plugins/org.polarsys.capella.core.transition.common.ui/src/org/polarsys/capella/core/transition/common/ui/handlers/merge/DiffCategoryProxy.java
Labels: build-successfull

#2577 #2576 Allow deletion of Sequence info on xAB diagrams
  core/plugins/org.polarsys.capella.core.sirius.analysis/description/context.odesign
  core/plugins/org.polarsys.capella.core.sirius.analysis/description/logical.odesign
  core/plugins/org.polarsys.capella.core.sirius.analysis/description/oa.odesign
  core/plugins/org.polarsys.capella.core.sirius.analysis/description/physical.odesign
  tests/plugins/org.polarsys.capella.test.diagram.common.ju/src/org/polarsys/capella/test/diagram/common/ju/context/XABDiagram.java
  tests/plugins/org.polarsys.capella.test.diagram.common.ju/src/org/polarsys/capella/test/diagram/common/ju/wrapper/utils/DiagramHelper.java
  tests/plugins/org.polarsys.capella.test.diagram.tools.ju/model/XABDiagrams/XABDiagrams.aird
  tests/plugins/org.polarsys.capella.test.diagram.tools.ju/model/XABDiagrams/XABDiagrams.capella
  tests/plugins/org.polarsys.capella.test.diagram.tools.ju/src/org/polarsys/capella/test/diagram/tools/ju/testsuites/partial/XABDiagramToolsTestSuite.java
  tests/plugins/org.polarsys.capella.test.diagram.tools.ju/src/org/polarsys/capella/test/diagram/tools/ju/xab/DeleteSequenceLink.java
  tests/plugins/org.polarsys.capella.test.diagram.tools.ju/src/org/polarsys/capella/test/diagram/tools/ju/xab/XABDiagramsProject.java
Labels: build-successfull

#2580 #2563 Select REC/RPL elements now works on edges
  common/plugins/org.polarsys.capella.common.re.ui/src/org/polarsys/capella/common/re/ui/menu/RecDynamicMenu.java
  common/plugins/org.polarsys.capella.common.re.ui/src/org/polarsys/capella/common/re/ui/menu/RplDynamicMenu.java
  doc/plugins/org.polarsys.capella.re.doc/html/08. Replicable Element (REC-RPL)/8.2. Basic Use Case.html
  doc/plugins/org.polarsys.capella.re.doc/html/08. Replicable Element (REC-RPL)/8.2. Basic Use Case.mediawiki
  doc/plugins/org.polarsys.capella.re.doc/html/08. Replicable Element (REC-RPL)/8.6. Advanced Features.html
  doc/plugins/org.polarsys.capella.re.doc/html/08. Replicable Element (REC-RPL)/8.6. Advanced Features.mediawiki
  doc/plugins/org.polarsys.capella.tipsandtricks.doc/html/Tips and tricks/5_Layout management/5_Layout management.html
  doc/plugins/org.polarsys.capella.tipsandtricks.doc/html/Tips and tricks/5_Layout management/5_Layout management.mediawiki
  doc/plugins/org.polarsys.capella.tipsandtricks.doc/html/Tips and tricks/6_Diagram exploration/6_Diagram exploration.html
  doc/plugins/org.polarsys.capella.tipsandtricks.doc/html/Tips and tricks/6_Diagram exploration/6_Diagram exploration.mediawiki
  tests/plugins/org.polarsys.capella.test.diagram.tools.ju/src/org/polarsys/capella/test/diagram/tools/ju/common/SelectToolsTest.java
Labels: build-successfull

#2586 [releng] Update to Sirius 7.1.0-S20230210-122000
  releng/plugins/org.polarsys.capella.targets/full/capella.target-definition.targetplatform
Labels: build-successfull

#2588 [releng] Update Kitalpha 6.1.0.20230213
  releng/plugins/org.polarsys.capella.targets/full/capella.target-definition.targetplatform
Labels: build-successfull

#2589 #2567 Dummy fixes on Capella right click menus
  core/plugins/org.polarsys.capella.core.platform.sirius.ui.menu/plugin.xml
  core/plugins/org.polarsys.capella.core.sirius.ui/src/org/polarsys/capella/core/sirius/ui/testers/ValidCECategoryMenuTargetTester.java
Labels: build-successfull

#2591 [#2590] improved list of default views
  core/plugins/org.polarsys.capella.core.platform.sirius.ui.perspective/plugin.xml
  doc/plugins/org.polarsys.capella.ui.doc/html/First steps with Capella/Images/3.1. Starting Melody Advance_html_15a02c99.png
  doc/plugins/org.polarsys.capella.viewpoint.doc/html/Images/Windows_ShowView.png
Labels: build-successfull

#2592 #2587 fix regressions :
  core/plugins/org.polarsys.capella.core.sirius.ui/src/org/polarsys/capella/core/sirius/ui/handlers/CreateFunctionalChainActionHandler.java
  core/plugins/org.polarsys.capella.core.sirius.ui/src/org/polarsys/capella/core/sirius/ui/handlers/CreatePhysicalPathActionHandler.java
  core/plugins/org.polarsys.capella.core.sirius.ui/src/org/polarsys/capella/core/sirius/ui/testers/AbstractValidCategoryMenuTargetTester.java
  core/plugins/org.polarsys.capella.core.sirius.ui/src/org/polarsys/capella/core/sirius/ui/testers/ValidFCMenuTargetTester.java
  core/plugins/org.polarsys.capella.core.sirius.ui/src/org/polarsys/capella/core/sirius/ui/testers/ValidPPMenuTargetTester.java
Labels: build-successfull

#2601 #2600 Fixed double-click navigation not working on Team
  core/plugins/org.polarsys.capella.core.sirius.analysis/src/org/polarsys/capella/core/sirius/analysis/policies/OpenRelatedDiagramEditPolicy.java
Labels: build-successfull

#2604 #2596 Fixed regression on diagram opening
  core/plugins/org.polarsys.capella.core.platform.sirius.ui.navigator/src/org/polarsys/capella/core/platform/sirius/ui/navigator/actions/OpenAction.java
Labels: build-successfull
